"""Pydantic models generated from Keepa backend Java structs."""

# Generated by utilities/generate-backend-models.py; do not edit by hand.

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field

BACKEND_COMMIT = "6e524d13bc25bdbe49be24d59a4b28feb9f98e5d"


class KeepaBackendModel(BaseModel):
    """Base model for backend response/request structures."""

    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)


class AmazonLocale(str, Enum):
    """Backend enum generated from the Keepa Java schema."""

    RESERVED = "RESERVED"
    US = "US"
    GB = "GB"
    DE = "DE"
    FR = "FR"
    JP = "JP"
    CA = "CA"
    RESERVED2 = "RESERVED2"
    IT = "IT"
    ES = "ES"
    IN = "IN"
    MX = "MX"
    BR = "BR"


class AvailabilityType(str, Enum):
    """Backend enum generated from the Keepa Java schema."""

    NO_OFFER = "NO_OFFER"
    NOW = "NOW"
    PREORDERABLE = "PREORDERABLE"
    UNKNOWN = "UNKNOWN"
    BACKORDERABLE = "BACKORDERABLE"
    DELAYED = "DELAYED"


class CsvType(str, Enum):
    """Backend enum generated from the Keepa Java schema."""

    AMAZON = "AMAZON"
    NEW = "NEW"
    USED = "USED"
    SALES = "SALES"
    LISTPRICE = "LISTPRICE"
    COLLECTIBLE = "COLLECTIBLE"
    REFURBISHED = "REFURBISHED"
    NEW_FBM_SHIPPING = "NEW_FBM_SHIPPING"
    LIGHTNING_DEAL = "LIGHTNING_DEAL"
    WAREHOUSE = "WAREHOUSE"
    NEW_FBA = "NEW_FBA"
    COUNT_NEW = "COUNT_NEW"
    COUNT_USED = "COUNT_USED"
    COUNT_REFURBISHED = "COUNT_REFURBISHED"
    COUNT_COLLECTIBLE = "COUNT_COLLECTIBLE"
    EXTRA_INFO_UPDATES = "EXTRA_INFO_UPDATES"
    RATING = "RATING"
    COUNT_REVIEWS = "COUNT_REVIEWS"
    BUY_BOX_SHIPPING = "BUY_BOX_SHIPPING"
    USED_NEW_SHIPPING = "USED_NEW_SHIPPING"
    USED_VERY_GOOD_SHIPPING = "USED_VERY_GOOD_SHIPPING"
    USED_GOOD_SHIPPING = "USED_GOOD_SHIPPING"
    USED_ACCEPTABLE_SHIPPING = "USED_ACCEPTABLE_SHIPPING"
    COLLECTIBLE_NEW_SHIPPING = "COLLECTIBLE_NEW_SHIPPING"
    COLLECTIBLE_VERY_GOOD_SHIPPING = "COLLECTIBLE_VERY_GOOD_SHIPPING"
    COLLECTIBLE_GOOD_SHIPPING = "COLLECTIBLE_GOOD_SHIPPING"
    COLLECTIBLE_ACCEPTABLE_SHIPPING = "COLLECTIBLE_ACCEPTABLE_SHIPPING"
    REFURBISHED_SHIPPING = "REFURBISHED_SHIPPING"
    EBAY_NEW_SHIPPING = "EBAY_NEW_SHIPPING"
    EBAY_USED_SHIPPING = "EBAY_USED_SHIPPING"
    TRADE_IN = "TRADE_IN"
    RENT = "RENT"
    BUY_BOX_USED_SHIPPING = "BUY_BOX_USED_SHIPPING"
    PRIME_EXCL = "PRIME_EXCL"
    COUNT_NEW_FBA = "COUNT_NEW_FBA"
    COUNT_NEW_FBM = "COUNT_NEW_FBM"


class DealInterval(str, Enum):
    """Backend enum generated from the Keepa Java schema."""

    DAY = "DAY"
    WEEK = "WEEK"
    MONTH = "MONTH"
    _90_DAYS = "_90_DAYS"


class DealState(str, Enum):
    """Backend enum generated from the Keepa Java schema."""

    AVAILABLE = "AVAILABLE"
    UPCOMING = "UPCOMING"
    WAITLIST = "WAITLIST"
    SOLDOUT = "SOLDOUT"
    WAITLISTFULL = "WAITLISTFULL"
    EXPIRED = "EXPIRED"
    SUPPRESSED = "SUPPRESSED"


class MerchantCsvType(str, Enum):
    """Backend enum generated from the Keepa Java schema."""

    RATING = "RATING"
    RATING_COUNT = "RATING_COUNT"


class NotificationType(str, Enum):
    """Backend enum generated from the Keepa Java schema."""

    EMAIL = "EMAIL"
    TWITTER = "TWITTER"
    FACEBOOK_NOTIFICATION = "FACEBOOK_NOTIFICATION"
    BROWSER = "BROWSER"
    FACEBOOK_MESSENGER_BOT = "FACEBOOK_MESSENGER_BOT"
    API = "API"
    MOBILE_APP = "MOBILE_APP"
    DUMMY = "DUMMY"


class NotifyIfType(str, Enum):
    """Backend enum generated from the Keepa Java schema."""

    OUT_OF_STOCK = "OUT_OF_STOCK"
    BACK_IN_STOCK = "BACK_IN_STOCK"


class OfferCondition(str, Enum):
    """Backend enum generated from the Keepa Java schema."""

    UNKNOWN = "UNKNOWN"
    NEW = "NEW"
    USED_NEW = "USED_NEW"
    USED_VERY_GOOD = "USED_VERY_GOOD"
    USED_GOOD = "USED_GOOD"
    USED_ACCEPTABLE = "USED_ACCEPTABLE"
    REFURBISHED = "REFURBISHED"
    COLLECTIBLE_NEW = "COLLECTIBLE_NEW"
    COLLECTIBLE_VERY_GOOD = "COLLECTIBLE_VERY_GOOD"
    COLLECTIBLE_GOOD = "COLLECTIBLE_GOOD"
    COLLECTIBLE_ACCEPTABLE = "COLLECTIBLE_ACCEPTABLE"


class ProductType(str, Enum):
    """Backend enum generated from the Keepa Java schema."""

    STANDARD = "STANDARD"
    DOWNLOADABLE = "DOWNLOADABLE"
    EBOOK = "EBOOK"
    UNACCESSIBLE = "UNACCESSIBLE"
    INVALID = "INVALID"
    VARIATION_PARENT = "VARIATION_PARENT"


class PromotionType(str, Enum):
    """Backend enum generated from the Keepa Java schema."""

    SNS = "SNS"
    PrimeExclusive = "PrimeExclusive"


class ResponseStatus(str, Enum):
    """Backend enum generated from the Keepa Java schema."""

    PENDING = "PENDING"
    OK = "OK"
    FAIL = "FAIL"
    NOT_ENOUGH_TOKEN = "NOT_ENOUGH_TOKEN"
    REQUEST_REJECTED = "REQUEST_REJECTED"
    NOT_FOUND = "NOT_FOUND"
    PAYMENT_REQUIRED = "PAYMENT_REQUIRED"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"


class TrackingNotificationCause(str, Enum):
    """Backend enum generated from the Keepa Java schema."""

    EXPIRED = "EXPIRED"
    DESIRED_PRICE = "DESIRED_PRICE"
    PRICE_CHANGE = "PRICE_CHANGE"
    PRICE_CHANGE_AFTER_DESIRED_PRICE = "PRICE_CHANGE_AFTER_DESIRED_PRICE"
    OUT_STOCK = "OUT_STOCK"
    IN_STOCK = "IN_STOCK"
    DESIRED_PRICE_AGAIN = "DESIRED_PRICE_AGAIN"


class VideoCreatorType(str, Enum):
    """Backend enum generated from the Keepa Java schema."""

    Main = "Main"
    Customer = "Customer"
    Seller = "Seller"
    Influencer = "Influencer"
    Vendor = "Vendor"
    ThirdParty = "ThirdParty"
    Amazon = "Amazon"
    Merchant = "Merchant"
    Brand = "Brand"


class APlus(KeepaBackendModel):
    """Backend ``APlus`` model generated from the Keepa Java schema."""

    module: list[APlusModule | None] | None = None
    fromManufacturer: bool | None = None


class APlusModule(KeepaBackendModel):
    """Backend ``APlusModule`` model generated from the Keepa Java schema."""

    text: list[str | None] | None = None
    image: list[str | None] | None = None
    video: list[str | None] | None = None
    imageAltText: list[str | None] | None = None
    asin: list[str | None] | None = None


class BestSellers(KeepaBackendModel):
    """Backend ``BestSellers`` model generated from the Keepa Java schema."""

    domainId: int | None = None
    lastUpdate: int | None = None
    categoryId: int | None = None
    asinList: list[str | None] | None = None


class BuyBoxStatsObject(KeepaBackendModel):
    """Backend ``BuyBoxStatsObject`` model generated from the Keepa Java schema."""

    percentageWon: float | None = None
    avgPrice: int | None = None
    avgNewOfferCount: int | None = None
    isFBA: bool | None = None
    lastSeen: int | None = None


class Category(KeepaBackendModel):
    """Backend ``Category`` model generated from the Keepa Java schema."""

    domainId: int | None = None
    catId: int | None = None
    name: str | None = None
    contextFreeName: str | None = None
    websiteDisplayGroup: str | None = None
    children: list[int | None] | None = None
    parent: int | None = None
    highestRank: int | None = None
    lowestRank: int | None = None
    productCount: int | None = None
    isBrowseNode: bool | None = None
    avgBuyBox: int | None = None
    avgBuyBox90: int | None = None
    avgBuyBox365: int | None = None
    avgBuyBoxDeviation: int | None = None
    avgReviewCount: int | None = None
    avgRating: int | None = None
    isFBAPercent: float | None = None
    soldByAmazonPercent: float | None = None
    hasCouponPercent: float | None = None
    avgOfferCountNew: float | None = None
    avgOfferCountUsed: float | None = None
    sellerCount: int | None = None
    brandCount: int | None = None


class CategoryTreeEntry(KeepaBackendModel):
    """Backend ``CategoryTreeEntry`` model generated from the Keepa Java schema."""

    catId: int | None = None
    name: str | None = None


class Competitors(KeepaBackendModel):
    """Backend ``Competitors`` model generated from the Keepa Java schema."""

    sellerId: str | None = None
    percent: int | None = None


class Deal(KeepaBackendModel):
    """Backend ``Deal`` model generated from the Keepa Java schema."""

    asin: str | None = None
    parentAsin: str | None = None
    title: str | None = None
    delta: list[list[int | None] | None] | None = None
    deltaPercent: list[list[int | None] | None] | None = None
    deltaLast: list[int | None] | None = None
    avg: list[list[int | None] | None] | None = None
    current: list[int | None] | None = None
    rootCat: int | None = None
    creationDate: int | None = None
    image: list[int | None] | None = None
    categories: list[int | None] | None = None
    lastUpdate: int | None = None
    lightningEnd: int | None = None
    minRating: int | None = None
    warehouseCondition: int | None = None
    warehouseConditionComment: str | None = None
    currentSince: list[int | None] | None = None


class DealDetails(KeepaBackendModel):
    """Backend ``DealDetails`` model generated from the Keepa Java schema."""

    accessType: str | None = None
    endTime: int | None = None
    startTime: int | None = None
    percentClaimed: int | None = None
    badge: str | None = None
    dealType: str | None = None


class DealRequest(KeepaBackendModel):
    """Backend ``DealRequest`` model generated from the Keepa Java schema."""

    page: int | None = None
    domainId: int | None = None
    priceTypes: list[int | None] | None = None
    isLowest: bool | None = None
    isLowest90: bool | None = None
    isLowestOffer: bool | None = None
    dateRange: int | None = None
    deltaRange: list[int | None] | None = None
    excludeCategories: list[int | None] | None = None
    includeCategories: list[int | None] | None = None
    deltaPercentRange: list[int | None] | None = None
    currentRange: list[int | None] | None = None
    titleSearch: str | None = None
    isBackInStock: bool | None = None
    isOutOfStock: bool | None = None
    isRangeEnabled: bool | None = None
    filterErotic: bool | None = None
    sortType: int | None = None
    salesRankRange: list[int | None] | None = None
    isFilterEnabled: bool | None = None
    deltaLastRange: list[int | None] | None = None
    hasReviews: bool | None = None
    isPrimeExclusive: bool | None = None
    mustHaveAmazonOffer: bool | None = None
    mustNotHaveAmazonOffer: bool | None = None
    minRating: int | None = None
    warehouseConditions: list[int | None] | None = None
    singleVariation: bool | None = None
    material: list[str | None] | None = None
    type: list[str | None] | None = None
    manufacturer: list[str | None] | None = None
    brand: list[str | None] | None = None
    productGroup: list[str | None] | None = None
    model: list[str | None] | None = None
    color: list[str | None] | None = None
    size: list[str | None] | None = None
    unitType: list[str | None] | None = None
    scent: list[str | None] | None = None
    itemForm: list[str | None] | None = None
    pattern: list[str | None] | None = None
    style: list[str | None] | None = None
    itemTypeKeyword: list[str | None] | None = None
    targetAudienceKeyword: list[str | None] | None = None
    edition: list[str | None] | None = None
    format: list[str | None] | None = None
    author: list[str | None] | None = None
    binding: list[str | None] | None = None
    languages: list[str | None] | None = None
    brandStoreName: list[str | None] | None = None
    brandStoreUrlName: list[str | None] | None = None
    websiteDisplayGroup: list[str | None] | None = None
    websiteDisplayGroupName: list[str | None] | None = None
    salesRankDisplayGroup: list[str | None] | None = None


class DealResponse(KeepaBackendModel):
    """Backend ``DealResponse`` model generated from the Keepa Java schema."""

    dr: list[Deal | None] | None = None
    drDateIndex: list[int | None] | None = None
    categoryIds: list[int | None] | None = None
    categoryNames: list[str | None] | None = None
    categoryCount: list[int | None] | None = None


class FBAFeesObject(KeepaBackendModel):
    """Backend ``FBAFeesObject`` model generated from the Keepa Java schema."""

    storageFee: int | None = None
    storageFeeTax: int | None = None
    pickAndPackFee: int | None = None
    pickAndPackFeeTax: int | None = None


class FeedbackObject(KeepaBackendModel):
    """Backend ``FeedbackObject`` model generated from the Keepa Java schema."""

    rating: int | None = None
    date: int | None = None
    feedback: str | None = None
    isStriked: bool | None = None


class Format(KeepaBackendModel):
    """Backend ``Format`` model generated from the Keepa Java schema."""

    asin: str | None = None
    format: str | None = None


class HazardousMaterial(KeepaBackendModel):
    """Backend ``HazardousMaterial`` model generated from the Keepa Java schema."""

    aspect: str | None = None
    value: str | None = None


class Image(KeepaBackendModel):
    """Backend ``Image`` model generated from the Keepa Java schema."""

    l_: str | None = Field(default=None, alias="l")
    lH: int | None = None
    lW: int | None = None
    m: str | None = None
    mH: int | None = None
    mW: int | None = None


class LightningDeal(KeepaBackendModel):
    """Backend ``LightningDeal`` model generated from the Keepa Java schema."""

    domainId: int | None = None
    lastUpdate: int | None = None
    asin: str | None = None
    title: str | None = None
    sellerName: str | None = None
    sellerId: str | None = None
    dealId: str | None = None
    dealPrice: int | None = None
    currentPrice: int | None = None
    image: str | None = None
    isPrimeEligible: bool | None = None
    isFulfilledByAmazon: bool | None = None
    isMAP: bool | None = None
    rating: int | None = None
    totalReviews: int | None = None
    dealState: DealState | None = None
    startTime: int | None = None
    endTime: int | None = None
    percentClaimed: int | None = None
    percentOff: int | None = None
    variation: list[VariationAttributeObject | None] | None = None


class MerchantBrandStatistics(KeepaBackendModel):
    """Backend ``MerchantBrandStatistics`` model generated from the Keepa Java schema."""

    brand: str | None = None
    productCount: int | None = None
    avg30SalesRank: int | None = None
    productCountWithAmazonOffer: int | None = None


class MerchantCategoryStatistics(KeepaBackendModel):
    """Backend ``MerchantCategoryStatistics`` model generated from the Keepa Java schema."""

    catId: int | None = None
    productCount: int | None = None
    avg30SalesRank: int | None = None
    productCountWithAmazonOffer: int | None = None


class Notification(KeepaBackendModel):
    """Backend ``Notification`` model generated from the Keepa Java schema."""

    asin: str | None = None
    title: str | None = None
    image: str | None = None
    createDate: int | None = None
    domainId: int | None = None
    notificationDomainId: int | None = None
    csvType: int | None = None
    trackingNotificationCause: int | None = None
    currentPrices: list[int | None] | None = None
    sentNotificationVia: list[bool | None] | None = None
    metaData: str | None = None


class Offer(KeepaBackendModel):
    """Backend ``Offer`` model generated from the Keepa Java schema."""

    offerId: int | None = None
    lastSeen: int | None = None
    sellerId: str | None = None
    offerCSV: list[int | None] | None = None
    condition: int | None = None
    conditionComment: str | None = None
    isPrime: bool | None = None
    isMAP: bool | None = None
    isShippable: bool | None = None
    isPreorder: bool | None = None
    isWarehouseDeal: bool | None = None
    shipsFromChina: bool | None = None
    isAmazon: bool | None = None
    isFBA: bool | None = None
    isPrimeExcl: bool | None = None
    primeExclCSV: list[int | None] | None = None
    stockCSV: list[int | None] | None = None
    minOrderQty: int | None = None
    coupon: int | None = None
    couponHistory: list[int | None] | None = None
    offerDuplicates: list[OfferDuplicate | None] | None = None


class OfferDuplicate(KeepaBackendModel):
    """Backend ``OfferDuplicate`` model generated from the Keepa Java schema."""

    price: int | None = None
    conditionComment: str | None = None
    shipping: int | None = None


class Product(KeepaBackendModel):
    """Backend ``Product`` model generated from the Keepa Java schema."""

    asin: str | None = None
    domainId: int | None = None
    parentAsin: str | None = None
    parentAsinHistory: list[str | None] | None = None
    variationCSV: str | None = None
    upcList: list[str | None] | None = None
    eanList: list[str | None] | None = None
    gtinList: list[str | None] | None = None
    bundleItems: list[str | None] | None = None
    historicalVariations: list[str | None] | None = None
    imagesCSV: str | None = None
    images: list[Image | None] | None = None
    categories: list[int | None] | None = None
    rootCategory: int | None = None
    manufacturer: str | None = None
    title: str | None = None
    trackingSince: int | None = None
    listedSince: int | None = None
    brand: str | None = None
    productGroup: str | None = None
    partNumber: str | None = None
    model: str | None = None
    color: str | None = None
    size: str | None = None
    edition: str | None = None
    format: str | None = None
    author: str | None = None
    binding: str | None = None
    categoryTree: list[CategoryTreeEntry | None] | None = None
    numberOfItems: int | None = None
    numberOfPages: int | None = None
    publicationDate: int | None = None
    releaseDate: int | None = None
    languages: list[list[str | None] | None] | None = None
    contributors: list[list[str | None] | None] | None = None
    features: list[str | None] | None = None
    description: str | None = None
    packageHeight: int | None = None
    packageLength: int | None = None
    packageWidth: int | None = None
    packageWeight: int | None = None
    packageQuantity: int | None = None
    itemHeight: int | None = None
    itemLength: int | None = None
    itemWidth: int | None = None
    itemWeight: int | None = None
    ebayListingIds: list[int | None] | None = None
    isAdultProduct: bool | None = None
    isEligibleForTradeIn: bool | None = None
    referralFeePercent: int | None = None
    variableClosingFee: int | None = None
    urlSlug: str | None = None
    ingredients: str | None = None
    isHaul: bool | None = None
    referralFeePercentage: float | None = None
    lastSoldUpdate: int | None = None
    monthlySold: int | None = None
    monthlySoldHistory: list[int | None] | None = None
    isEligibleForSuperSaverShipping: bool | None = None
    lastUpdate: int | None = None
    lastPriceChange: int | None = None
    lastEbayUpdate: int | None = None
    lastStockUpdate: int | None = None
    lastRatingUpdate: int | None = None
    productType: int | None = None
    type: str | None = None
    hasReviews: bool | None = None
    reviews: ReviewObject | None = None
    stats: Stats | None = None
    offers: list[Offer | None] | None = None
    liveOffersOrder: list[int | None] | None = None
    buyBoxSellerIdHistory: list[str | None] | None = None
    buyBoxUsedHistory: list[str | None] | None = None
    isRedirectASIN: bool | None = None
    isSNS: bool | None = None
    suggestedLowerPrice: int | None = None
    competitivePriceThreshold: int | None = None
    buyBoxEligibleOfferCounts: list[int | None] | None = None
    hazardousMaterials: list[HazardousMaterial | None] | None = None
    offersSuccessful: bool | None = None
    frequentlyBoughtTogether: list[str | None] | None = None
    isMerchOnDemand: bool | None = None
    isHeatSensitive: bool | None = None
    returnRate: int | None = None
    promotions: list[PromotionObject | None] | None = None
    variations: list[VariationObject | None] | None = None
    availabilityAmazon: int | None = None
    coupon: list[int | None] | None = None
    couponHistory: list[int | None] | None = None
    newPriceIsMAP: bool | None = None
    fbaFees: FBAFeesObject | None = None
    salesRanks: dict[int, list[int | None] | None] | None = None
    salesRankReference: int | None = None
    salesRankReferenceHistory: list[int | None] | None = None
    availabilityAmazonDelay: list[int | None] | None = None
    audienceRating: str | None = None
    unitCount: UnitCountObject | None = None
    scent: str | None = None
    shortDescription: str | None = None
    activeIngredients: str | None = None
    specialIngredients: str | None = None
    itemForm: str | None = None
    itemTypeKeyword: str | None = None
    recommendedUsesForProduct: str | None = None
    pattern: str | None = None
    brandStoreName: str | None = None
    brandStoreUrl: str | None = None
    brandStoreUrlName: str | None = None
    videos: list[Video | None] | None = None
    aPlus: list[APlus | None] | None = None
    specificUsesForProduct: list[str | None] | None = None
    websiteDisplayGroupName: str | None = None
    websiteDisplayGroup: str | None = None
    formats: list[Format | None] | None = None
    businessDiscount: int | None = None
    lastBusinessDiscountUpdate: int | None = None
    safetyWarning: str | None = None
    productBenefit: str | None = None
    batteriesRequired: bool | None = None
    batteriesIncluded: bool | None = None
    targetAudienceKeyword: str | None = None
    style: str | None = None
    includedComponents: str | None = None
    materials: list[str | None] | None = None
    material: str | None = None
    specialFeatures: list[str | None] | None = None
    deals: list[DealDetails | None] | None = None
    csv: list[list[int | None] | None] | None = None


class ProductFinderRequest(KeepaBackendModel):
    """Backend ``ProductFinderRequest`` model generated from the Keepa Java schema."""

    author: list[str | None] | None = None
    availabilityAmazon: list[int | None] | None = None
    avg365_AMAZON_lte: int | None = None
    avg365_AMAZON_gte: int | None = None
    avg365_BUY_BOX_SHIPPING_lte: int | None = None
    avg365_BUY_BOX_SHIPPING_gte: int | None = None
    avg365_BUY_BOX_USED_SHIPPING_lte: int | None = None
    avg365_BUY_BOX_USED_SHIPPING_gte: int | None = None
    avg365_COLLECTIBLE_lte: int | None = None
    avg365_COLLECTIBLE_gte: int | None = None
    avg365_COUNT_COLLECTIBLE_lte: int | None = None
    avg365_COUNT_COLLECTIBLE_gte: int | None = None
    avg365_COUNT_NEW_lte: int | None = None
    avg365_COUNT_NEW_gte: int | None = None
    avg365_COUNT_REFURBISHED_lte: int | None = None
    avg365_COUNT_REFURBISHED_gte: int | None = None
    avg365_COUNT_REVIEWS_lte: int | None = None
    avg365_COUNT_REVIEWS_gte: int | None = None
    avg365_COUNT_USED_lte: int | None = None
    avg365_COUNT_USED_gte: int | None = None
    avg365_EBAY_NEW_SHIPPING_lte: int | None = None
    avg365_EBAY_NEW_SHIPPING_gte: int | None = None
    avg365_EBAY_USED_SHIPPING_lte: int | None = None
    avg365_EBAY_USED_SHIPPING_gte: int | None = None
    avg365_LIGHTNING_DEAL_lte: int | None = None
    avg365_LIGHTNING_DEAL_gte: int | None = None
    avg365_LISTPRICE_lte: int | None = None
    avg365_LISTPRICE_gte: int | None = None
    avg365_NEW_lte: int | None = None
    avg365_NEW_gte: int | None = None
    avg365_NEW_FBA_lte: int | None = None
    avg365_NEW_FBA_gte: int | None = None
    avg365_NEW_FBM_SHIPPING_lte: int | None = None
    avg365_NEW_FBM_SHIPPING_gte: int | None = None
    avg365_PRIME_EXCL_lte: int | None = None
    avg365_PRIME_EXCL_gte: int | None = None
    avg365_RATING_lte: int | None = None
    avg365_RATING_gte: int | None = None
    avg365_REFURBISHED_lte: int | None = None
    avg365_REFURBISHED_gte: int | None = None
    avg365_REFURBISHED_SHIPPING_lte: int | None = None
    avg365_REFURBISHED_SHIPPING_gte: int | None = None
    avg365_RENT_lte: int | None = None
    avg365_RENT_gte: int | None = None
    avg365_SALES_lte: int | None = None
    avg365_SALES_gte: int | None = None
    avg365_TRADE_IN_lte: int | None = None
    avg365_TRADE_IN_gte: int | None = None
    avg365_USED_lte: int | None = None
    avg365_USED_gte: int | None = None
    avg365_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    avg365_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    avg365_USED_GOOD_SHIPPING_lte: int | None = None
    avg365_USED_GOOD_SHIPPING_gte: int | None = None
    avg365_USED_NEW_SHIPPING_lte: int | None = None
    avg365_USED_NEW_SHIPPING_gte: int | None = None
    avg365_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    avg365_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    avg365_WAREHOUSE_lte: int | None = None
    avg365_WAREHOUSE_gte: int | None = None
    avg180_AMAZON_lte: int | None = None
    avg180_AMAZON_gte: int | None = None
    avg180_BUY_BOX_SHIPPING_lte: int | None = None
    avg180_BUY_BOX_SHIPPING_gte: int | None = None
    avg180_BUY_BOX_USED_SHIPPING_lte: int | None = None
    avg180_BUY_BOX_USED_SHIPPING_gte: int | None = None
    avg180_COLLECTIBLE_lte: int | None = None
    avg180_COLLECTIBLE_gte: int | None = None
    avg180_COUNT_COLLECTIBLE_lte: int | None = None
    avg180_COUNT_COLLECTIBLE_gte: int | None = None
    avg180_COUNT_NEW_lte: int | None = None
    avg180_COUNT_NEW_gte: int | None = None
    avg180_COUNT_REFURBISHED_lte: int | None = None
    avg180_COUNT_REFURBISHED_gte: int | None = None
    avg180_COUNT_REVIEWS_lte: int | None = None
    avg180_COUNT_REVIEWS_gte: int | None = None
    avg180_COUNT_USED_lte: int | None = None
    avg180_COUNT_USED_gte: int | None = None
    avg180_EBAY_NEW_SHIPPING_lte: int | None = None
    avg180_EBAY_NEW_SHIPPING_gte: int | None = None
    avg180_EBAY_USED_SHIPPING_lte: int | None = None
    avg180_EBAY_USED_SHIPPING_gte: int | None = None
    avg180_LIGHTNING_DEAL_lte: int | None = None
    avg180_LIGHTNING_DEAL_gte: int | None = None
    avg180_LISTPRICE_lte: int | None = None
    avg180_LISTPRICE_gte: int | None = None
    avg180_NEW_lte: int | None = None
    avg180_NEW_gte: int | None = None
    avg180_NEW_FBA_lte: int | None = None
    avg180_NEW_FBA_gte: int | None = None
    avg180_NEW_FBM_SHIPPING_lte: int | None = None
    avg180_NEW_FBM_SHIPPING_gte: int | None = None
    avg180_PRIME_EXCL_lte: int | None = None
    avg180_PRIME_EXCL_gte: int | None = None
    avg180_RATING_lte: int | None = None
    avg180_RATING_gte: int | None = None
    avg180_REFURBISHED_lte: int | None = None
    avg180_REFURBISHED_gte: int | None = None
    avg180_REFURBISHED_SHIPPING_lte: int | None = None
    avg180_REFURBISHED_SHIPPING_gte: int | None = None
    avg180_RENT_lte: int | None = None
    avg180_RENT_gte: int | None = None
    avg180_SALES_lte: int | None = None
    avg180_SALES_gte: int | None = None
    avg180_TRADE_IN_lte: int | None = None
    avg180_TRADE_IN_gte: int | None = None
    avg180_USED_lte: int | None = None
    avg180_USED_gte: int | None = None
    avg180_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    avg180_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    avg180_USED_GOOD_SHIPPING_lte: int | None = None
    avg180_USED_GOOD_SHIPPING_gte: int | None = None
    avg180_USED_NEW_SHIPPING_lte: int | None = None
    avg180_USED_NEW_SHIPPING_gte: int | None = None
    avg180_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    avg180_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    avg180_WAREHOUSE_lte: int | None = None
    avg180_WAREHOUSE_gte: int | None = None
    avg1_AMAZON_lte: int | None = None
    avg1_AMAZON_gte: int | None = None
    avg1_BUY_BOX_SHIPPING_lte: int | None = None
    avg1_BUY_BOX_SHIPPING_gte: int | None = None
    avg1_BUY_BOX_USED_SHIPPING_lte: int | None = None
    avg1_BUY_BOX_USED_SHIPPING_gte: int | None = None
    avg1_COLLECTIBLE_lte: int | None = None
    avg1_COLLECTIBLE_gte: int | None = None
    avg1_COUNT_COLLECTIBLE_lte: int | None = None
    avg1_COUNT_COLLECTIBLE_gte: int | None = None
    avg1_COUNT_NEW_lte: int | None = None
    avg1_COUNT_NEW_gte: int | None = None
    avg1_COUNT_REFURBISHED_lte: int | None = None
    avg1_COUNT_REFURBISHED_gte: int | None = None
    avg1_COUNT_REVIEWS_lte: int | None = None
    avg1_COUNT_REVIEWS_gte: int | None = None
    avg1_COUNT_USED_lte: int | None = None
    avg1_COUNT_USED_gte: int | None = None
    avg1_EBAY_NEW_SHIPPING_lte: int | None = None
    avg1_EBAY_NEW_SHIPPING_gte: int | None = None
    avg1_EBAY_USED_SHIPPING_lte: int | None = None
    avg1_EBAY_USED_SHIPPING_gte: int | None = None
    avg1_LIGHTNING_DEAL_lte: int | None = None
    avg1_LIGHTNING_DEAL_gte: int | None = None
    avg1_LISTPRICE_lte: int | None = None
    avg1_LISTPRICE_gte: int | None = None
    avg1_NEW_lte: int | None = None
    avg1_NEW_gte: int | None = None
    avg1_NEW_FBA_lte: int | None = None
    avg1_NEW_FBA_gte: int | None = None
    avg1_NEW_FBM_SHIPPING_lte: int | None = None
    avg1_NEW_FBM_SHIPPING_gte: int | None = None
    avg1_PRIME_EXCL_lte: int | None = None
    avg1_PRIME_EXCL_gte: int | None = None
    avg1_RATING_lte: int | None = None
    avg1_RATING_gte: int | None = None
    avg1_REFURBISHED_lte: int | None = None
    avg1_REFURBISHED_gte: int | None = None
    avg1_REFURBISHED_SHIPPING_lte: int | None = None
    avg1_REFURBISHED_SHIPPING_gte: int | None = None
    avg1_RENT_lte: int | None = None
    avg1_RENT_gte: int | None = None
    avg1_SALES_lte: int | None = None
    avg1_SALES_gte: int | None = None
    avg1_TRADE_IN_lte: int | None = None
    avg1_TRADE_IN_gte: int | None = None
    avg1_USED_lte: int | None = None
    avg1_USED_gte: int | None = None
    avg1_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    avg1_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    avg1_USED_GOOD_SHIPPING_lte: int | None = None
    avg1_USED_GOOD_SHIPPING_gte: int | None = None
    avg1_USED_NEW_SHIPPING_lte: int | None = None
    avg1_USED_NEW_SHIPPING_gte: int | None = None
    avg1_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    avg1_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    avg1_WAREHOUSE_lte: int | None = None
    avg1_WAREHOUSE_gte: int | None = None
    avg30_AMAZON_lte: int | None = None
    avg30_AMAZON_gte: int | None = None
    avg30_BUY_BOX_SHIPPING_lte: int | None = None
    avg30_BUY_BOX_SHIPPING_gte: int | None = None
    avg30_BUY_BOX_USED_SHIPPING_lte: int | None = None
    avg30_BUY_BOX_USED_SHIPPING_gte: int | None = None
    avg30_COLLECTIBLE_lte: int | None = None
    avg30_COLLECTIBLE_gte: int | None = None
    avg30_COUNT_COLLECTIBLE_lte: int | None = None
    avg30_COUNT_COLLECTIBLE_gte: int | None = None
    avg30_COUNT_NEW_lte: int | None = None
    avg30_COUNT_NEW_gte: int | None = None
    avg30_COUNT_REFURBISHED_lte: int | None = None
    avg30_COUNT_REFURBISHED_gte: int | None = None
    avg30_COUNT_REVIEWS_lte: int | None = None
    avg30_COUNT_REVIEWS_gte: int | None = None
    avg30_COUNT_USED_lte: int | None = None
    avg30_COUNT_USED_gte: int | None = None
    avg30_EBAY_NEW_SHIPPING_lte: int | None = None
    avg30_EBAY_NEW_SHIPPING_gte: int | None = None
    avg30_EBAY_USED_SHIPPING_lte: int | None = None
    avg30_EBAY_USED_SHIPPING_gte: int | None = None
    avg30_LIGHTNING_DEAL_lte: int | None = None
    avg30_LIGHTNING_DEAL_gte: int | None = None
    avg30_LISTPRICE_lte: int | None = None
    avg30_LISTPRICE_gte: int | None = None
    avg30_NEW_lte: int | None = None
    avg30_NEW_gte: int | None = None
    avg30_NEW_FBA_lte: int | None = None
    avg30_NEW_FBA_gte: int | None = None
    avg30_NEW_FBM_SHIPPING_lte: int | None = None
    avg30_NEW_FBM_SHIPPING_gte: int | None = None
    avg30_PRIME_EXCL_lte: int | None = None
    avg30_PRIME_EXCL_gte: int | None = None
    avg30_RATING_lte: int | None = None
    avg30_RATING_gte: int | None = None
    avg30_REFURBISHED_lte: int | None = None
    avg30_REFURBISHED_gte: int | None = None
    avg30_REFURBISHED_SHIPPING_lte: int | None = None
    avg30_REFURBISHED_SHIPPING_gte: int | None = None
    avg30_RENT_lte: int | None = None
    avg30_RENT_gte: int | None = None
    avg30_SALES_lte: int | None = None
    avg30_SALES_gte: int | None = None
    avg30_TRADE_IN_lte: int | None = None
    avg30_TRADE_IN_gte: int | None = None
    avg30_USED_lte: int | None = None
    avg30_USED_gte: int | None = None
    avg30_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    avg30_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    avg30_USED_GOOD_SHIPPING_lte: int | None = None
    avg30_USED_GOOD_SHIPPING_gte: int | None = None
    avg30_USED_NEW_SHIPPING_lte: int | None = None
    avg30_USED_NEW_SHIPPING_gte: int | None = None
    avg30_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    avg30_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    avg30_WAREHOUSE_lte: int | None = None
    avg30_WAREHOUSE_gte: int | None = None
    avg7_AMAZON_lte: int | None = None
    avg7_AMAZON_gte: int | None = None
    avg7_BUY_BOX_SHIPPING_lte: int | None = None
    avg7_BUY_BOX_SHIPPING_gte: int | None = None
    avg7_BUY_BOX_USED_SHIPPING_lte: int | None = None
    avg7_BUY_BOX_USED_SHIPPING_gte: int | None = None
    avg7_COLLECTIBLE_lte: int | None = None
    avg7_COLLECTIBLE_gte: int | None = None
    avg7_COUNT_COLLECTIBLE_lte: int | None = None
    avg7_COUNT_COLLECTIBLE_gte: int | None = None
    avg7_COUNT_NEW_lte: int | None = None
    avg7_COUNT_NEW_gte: int | None = None
    avg7_COUNT_REFURBISHED_lte: int | None = None
    avg7_COUNT_REFURBISHED_gte: int | None = None
    avg7_COUNT_REVIEWS_lte: int | None = None
    avg7_COUNT_REVIEWS_gte: int | None = None
    avg7_COUNT_USED_lte: int | None = None
    avg7_COUNT_USED_gte: int | None = None
    avg7_EBAY_NEW_SHIPPING_lte: int | None = None
    avg7_EBAY_NEW_SHIPPING_gte: int | None = None
    avg7_EBAY_USED_SHIPPING_lte: int | None = None
    avg7_EBAY_USED_SHIPPING_gte: int | None = None
    avg7_LIGHTNING_DEAL_lte: int | None = None
    avg7_LIGHTNING_DEAL_gte: int | None = None
    avg7_LISTPRICE_lte: int | None = None
    avg7_LISTPRICE_gte: int | None = None
    avg7_NEW_lte: int | None = None
    avg7_NEW_gte: int | None = None
    avg7_NEW_FBA_lte: int | None = None
    avg7_NEW_FBA_gte: int | None = None
    avg7_NEW_FBM_SHIPPING_lte: int | None = None
    avg7_NEW_FBM_SHIPPING_gte: int | None = None
    avg7_PRIME_EXCL_lte: int | None = None
    avg7_PRIME_EXCL_gte: int | None = None
    avg7_RATING_lte: int | None = None
    avg7_RATING_gte: int | None = None
    avg7_REFURBISHED_lte: int | None = None
    avg7_REFURBISHED_gte: int | None = None
    avg7_REFURBISHED_SHIPPING_lte: int | None = None
    avg7_REFURBISHED_SHIPPING_gte: int | None = None
    avg7_RENT_lte: int | None = None
    avg7_RENT_gte: int | None = None
    avg7_SALES_lte: int | None = None
    avg7_SALES_gte: int | None = None
    avg7_TRADE_IN_lte: int | None = None
    avg7_TRADE_IN_gte: int | None = None
    avg7_USED_lte: int | None = None
    avg7_USED_gte: int | None = None
    avg7_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    avg7_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    avg7_USED_GOOD_SHIPPING_lte: int | None = None
    avg7_USED_GOOD_SHIPPING_gte: int | None = None
    avg7_USED_NEW_SHIPPING_lte: int | None = None
    avg7_USED_NEW_SHIPPING_gte: int | None = None
    avg7_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    avg7_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    avg7_WAREHOUSE_lte: int | None = None
    avg7_WAREHOUSE_gte: int | None = None
    avg90_AMAZON_lte: int | None = None
    avg90_AMAZON_gte: int | None = None
    avg90_BUY_BOX_SHIPPING_lte: int | None = None
    avg90_BUY_BOX_SHIPPING_gte: int | None = None
    avg90_BUY_BOX_USED_SHIPPING_lte: int | None = None
    avg90_BUY_BOX_USED_SHIPPING_gte: int | None = None
    avg90_COLLECTIBLE_lte: int | None = None
    avg90_COLLECTIBLE_gte: int | None = None
    avg90_COUNT_COLLECTIBLE_lte: int | None = None
    avg90_COUNT_COLLECTIBLE_gte: int | None = None
    avg90_COUNT_NEW_lte: int | None = None
    avg90_COUNT_NEW_gte: int | None = None
    avg90_COUNT_REFURBISHED_lte: int | None = None
    avg90_COUNT_REFURBISHED_gte: int | None = None
    avg90_COUNT_REVIEWS_lte: int | None = None
    avg90_COUNT_REVIEWS_gte: int | None = None
    avg90_COUNT_USED_lte: int | None = None
    avg90_COUNT_USED_gte: int | None = None
    avg90_EBAY_NEW_SHIPPING_lte: int | None = None
    avg90_EBAY_NEW_SHIPPING_gte: int | None = None
    avg90_EBAY_USED_SHIPPING_lte: int | None = None
    avg90_EBAY_USED_SHIPPING_gte: int | None = None
    avg90_LIGHTNING_DEAL_lte: int | None = None
    avg90_LIGHTNING_DEAL_gte: int | None = None
    avg90_LISTPRICE_lte: int | None = None
    avg90_LISTPRICE_gte: int | None = None
    avg90_NEW_lte: int | None = None
    avg90_NEW_gte: int | None = None
    avg90_NEW_FBA_lte: int | None = None
    avg90_NEW_FBA_gte: int | None = None
    avg90_NEW_FBM_SHIPPING_lte: int | None = None
    avg90_NEW_FBM_SHIPPING_gte: int | None = None
    avg90_PRIME_EXCL_lte: int | None = None
    avg90_PRIME_EXCL_gte: int | None = None
    avg90_RATING_lte: int | None = None
    avg90_RATING_gte: int | None = None
    avg90_REFURBISHED_lte: int | None = None
    avg90_REFURBISHED_gte: int | None = None
    avg90_REFURBISHED_SHIPPING_lte: int | None = None
    avg90_REFURBISHED_SHIPPING_gte: int | None = None
    avg90_RENT_lte: int | None = None
    avg90_RENT_gte: int | None = None
    avg90_SALES_lte: int | None = None
    avg90_SALES_gte: int | None = None
    avg90_TRADE_IN_lte: int | None = None
    avg90_TRADE_IN_gte: int | None = None
    avg90_USED_lte: int | None = None
    avg90_USED_gte: int | None = None
    avg90_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    avg90_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    avg90_USED_GOOD_SHIPPING_lte: int | None = None
    avg90_USED_GOOD_SHIPPING_gte: int | None = None
    avg90_USED_NEW_SHIPPING_lte: int | None = None
    avg90_USED_NEW_SHIPPING_gte: int | None = None
    avg90_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    avg90_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    avg90_WAREHOUSE_lte: int | None = None
    avg90_WAREHOUSE_gte: int | None = None
    backInStock_AMAZON: bool | None = None
    backInStock_BUY_BOX_SHIPPING: bool | None = None
    backInStock_BUY_BOX_USED_SHIPPING: bool | None = None
    backInStock_COLLECTIBLE: bool | None = None
    backInStock_COUNT_COLLECTIBLE: bool | None = None
    backInStock_COUNT_NEW: bool | None = None
    backInStock_COUNT_REFURBISHED: bool | None = None
    backInStock_COUNT_REVIEWS: bool | None = None
    backInStock_COUNT_USED: bool | None = None
    backInStock_EBAY_NEW_SHIPPING: bool | None = None
    backInStock_EBAY_USED_SHIPPING: bool | None = None
    backInStock_LIGHTNING_DEAL: bool | None = None
    backInStock_LISTPRICE: bool | None = None
    backInStock_NEW: bool | None = None
    backInStock_NEW_FBA: bool | None = None
    backInStock_NEW_FBM_SHIPPING: bool | None = None
    backInStock_PRIME_EXCL: bool | None = None
    backInStock_RATING: bool | None = None
    backInStock_REFURBISHED: bool | None = None
    backInStock_REFURBISHED_SHIPPING: bool | None = None
    backInStock_RENT: bool | None = None
    backInStock_SALES: bool | None = None
    backInStock_TRADE_IN: bool | None = None
    backInStock_USED: bool | None = None
    backInStock_USED_ACCEPTABLE_SHIPPING: bool | None = None
    backInStock_USED_GOOD_SHIPPING: bool | None = None
    backInStock_USED_NEW_SHIPPING: bool | None = None
    backInStock_USED_VERY_GOOD_SHIPPING: bool | None = None
    backInStock_WAREHOUSE: bool | None = None
    binding: list[str | None] | None = None
    brand: list[str | None] | None = None
    dealType: list[str | None] | None = None
    buyBoxIsAmazon: bool | None = None
    buyBoxIsFBA: bool | None = None
    buyBoxIsUnqualified: bool | None = None
    buyBoxSellerId: list[str | None] | None = None
    buyBoxUsedCondition: list[int | None] | None = None
    buyBoxUsedIsFBA: bool | None = None
    buyBoxUsedSellerId: str | None = None
    categories_include: list[int | None] | None = None
    categories_exclude: list[int | None] | None = None
    color: list[str | None] | None = None
    historicalParentASIN: str | None = None
    couponOneTimeAbsolute_lte: int | None = None
    couponOneTimeAbsolute_gte: int | None = None
    couponOneTimePercent_lte: int | None = None
    couponOneTimePercent_gte: int | None = None
    couponSNSPercent_lte: int | None = None
    couponSNSPercent_gte: int | None = None
    current_AMAZON_lte: int | None = None
    current_AMAZON_gte: int | None = None
    current_BUY_BOX_SHIPPING_lte: int | None = None
    current_BUY_BOX_SHIPPING_gte: int | None = None
    current_BUY_BOX_USED_SHIPPING_lte: int | None = None
    current_BUY_BOX_USED_SHIPPING_gte: int | None = None
    current_COLLECTIBLE_lte: int | None = None
    current_COLLECTIBLE_gte: int | None = None
    current_COUNT_COLLECTIBLE_lte: int | None = None
    current_COUNT_COLLECTIBLE_gte: int | None = None
    current_COUNT_NEW_lte: int | None = None
    current_COUNT_NEW_gte: int | None = None
    current_COUNT_REFURBISHED_lte: int | None = None
    current_COUNT_REFURBISHED_gte: int | None = None
    current_COUNT_REVIEWS_lte: int | None = None
    current_COUNT_REVIEWS_gte: int | None = None
    current_COUNT_USED_lte: int | None = None
    current_COUNT_USED_gte: int | None = None
    current_EBAY_NEW_SHIPPING_lte: int | None = None
    current_EBAY_NEW_SHIPPING_gte: int | None = None
    current_EBAY_USED_SHIPPING_lte: int | None = None
    current_EBAY_USED_SHIPPING_gte: int | None = None
    current_LIGHTNING_DEAL_lte: int | None = None
    current_LIGHTNING_DEAL_gte: int | None = None
    current_LISTPRICE_lte: int | None = None
    current_LISTPRICE_gte: int | None = None
    current_NEW_lte: int | None = None
    current_NEW_gte: int | None = None
    current_NEW_FBA_lte: int | None = None
    current_NEW_FBA_gte: int | None = None
    current_NEW_FBM_SHIPPING_lte: int | None = None
    current_NEW_FBM_SHIPPING_gte: int | None = None
    current_PRIME_EXCL_lte: int | None = None
    current_PRIME_EXCL_gte: int | None = None
    current_RATING_lte: int | None = None
    current_RATING_gte: int | None = None
    current_REFURBISHED_lte: int | None = None
    current_REFURBISHED_gte: int | None = None
    current_REFURBISHED_SHIPPING_lte: int | None = None
    current_REFURBISHED_SHIPPING_gte: int | None = None
    current_RENT_lte: int | None = None
    current_RENT_gte: int | None = None
    current_SALES_lte: int | None = None
    current_SALES_gte: int | None = None
    current_TRADE_IN_lte: int | None = None
    current_TRADE_IN_gte: int | None = None
    current_USED_lte: int | None = None
    current_USED_gte: int | None = None
    current_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    current_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    current_USED_GOOD_SHIPPING_lte: int | None = None
    current_USED_GOOD_SHIPPING_gte: int | None = None
    current_USED_NEW_SHIPPING_lte: int | None = None
    current_USED_NEW_SHIPPING_gte: int | None = None
    current_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    current_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    current_WAREHOUSE_lte: int | None = None
    current_WAREHOUSE_gte: int | None = None
    delta1_AMAZON_lte: int | None = None
    delta1_AMAZON_gte: int | None = None
    delta1_BUY_BOX_SHIPPING_lte: int | None = None
    delta1_BUY_BOX_SHIPPING_gte: int | None = None
    delta1_BUY_BOX_USED_SHIPPING_lte: int | None = None
    delta1_BUY_BOX_USED_SHIPPING_gte: int | None = None
    delta1_COLLECTIBLE_lte: int | None = None
    delta1_COLLECTIBLE_gte: int | None = None
    delta1_COUNT_COLLECTIBLE_lte: int | None = None
    delta1_COUNT_COLLECTIBLE_gte: int | None = None
    delta1_COUNT_NEW_lte: int | None = None
    delta1_COUNT_NEW_gte: int | None = None
    delta1_COUNT_REFURBISHED_lte: int | None = None
    delta1_COUNT_REFURBISHED_gte: int | None = None
    delta1_COUNT_REVIEWS_lte: int | None = None
    delta1_COUNT_REVIEWS_gte: int | None = None
    delta1_COUNT_USED_lte: int | None = None
    delta1_COUNT_USED_gte: int | None = None
    delta1_EBAY_NEW_SHIPPING_lte: int | None = None
    delta1_EBAY_NEW_SHIPPING_gte: int | None = None
    delta1_EBAY_USED_SHIPPING_lte: int | None = None
    delta1_EBAY_USED_SHIPPING_gte: int | None = None
    delta1_LIGHTNING_DEAL_lte: int | None = None
    delta1_LIGHTNING_DEAL_gte: int | None = None
    delta1_LISTPRICE_lte: int | None = None
    delta1_LISTPRICE_gte: int | None = None
    delta1_NEW_lte: int | None = None
    delta1_NEW_gte: int | None = None
    delta1_NEW_FBA_lte: int | None = None
    delta1_NEW_FBA_gte: int | None = None
    delta1_NEW_FBM_SHIPPING_lte: int | None = None
    delta1_NEW_FBM_SHIPPING_gte: int | None = None
    delta1_PRIME_EXCL_lte: int | None = None
    delta1_PRIME_EXCL_gte: int | None = None
    delta1_RATING_lte: int | None = None
    delta1_RATING_gte: int | None = None
    delta1_REFURBISHED_lte: int | None = None
    delta1_REFURBISHED_gte: int | None = None
    delta1_REFURBISHED_SHIPPING_lte: int | None = None
    delta1_REFURBISHED_SHIPPING_gte: int | None = None
    delta1_RENT_lte: int | None = None
    delta1_RENT_gte: int | None = None
    delta1_SALES_lte: int | None = None
    delta1_SALES_gte: int | None = None
    delta1_TRADE_IN_lte: int | None = None
    delta1_TRADE_IN_gte: int | None = None
    delta1_USED_lte: int | None = None
    delta1_USED_gte: int | None = None
    delta1_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    delta1_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    delta1_USED_GOOD_SHIPPING_lte: int | None = None
    delta1_USED_GOOD_SHIPPING_gte: int | None = None
    delta1_USED_NEW_SHIPPING_lte: int | None = None
    delta1_USED_NEW_SHIPPING_gte: int | None = None
    delta1_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    delta1_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    delta1_WAREHOUSE_lte: int | None = None
    delta1_WAREHOUSE_gte: int | None = None
    delta30_AMAZON_lte: int | None = None
    delta30_AMAZON_gte: int | None = None
    delta30_BUY_BOX_SHIPPING_lte: int | None = None
    delta30_BUY_BOX_SHIPPING_gte: int | None = None
    delta30_BUY_BOX_USED_SHIPPING_lte: int | None = None
    delta30_BUY_BOX_USED_SHIPPING_gte: int | None = None
    delta30_COLLECTIBLE_lte: int | None = None
    delta30_COLLECTIBLE_gte: int | None = None
    delta30_COUNT_COLLECTIBLE_lte: int | None = None
    delta30_COUNT_COLLECTIBLE_gte: int | None = None
    delta30_COUNT_NEW_lte: int | None = None
    delta30_COUNT_NEW_gte: int | None = None
    delta30_COUNT_REFURBISHED_lte: int | None = None
    delta30_COUNT_REFURBISHED_gte: int | None = None
    delta30_COUNT_REVIEWS_lte: int | None = None
    delta30_COUNT_REVIEWS_gte: int | None = None
    delta30_COUNT_USED_lte: int | None = None
    delta30_COUNT_USED_gte: int | None = None
    delta30_EBAY_NEW_SHIPPING_lte: int | None = None
    delta30_EBAY_NEW_SHIPPING_gte: int | None = None
    delta30_EBAY_USED_SHIPPING_lte: int | None = None
    delta30_EBAY_USED_SHIPPING_gte: int | None = None
    delta30_LIGHTNING_DEAL_lte: int | None = None
    delta30_LIGHTNING_DEAL_gte: int | None = None
    delta30_LISTPRICE_lte: int | None = None
    delta30_LISTPRICE_gte: int | None = None
    delta30_NEW_lte: int | None = None
    delta30_NEW_gte: int | None = None
    delta30_NEW_FBA_lte: int | None = None
    delta30_NEW_FBA_gte: int | None = None
    delta30_NEW_FBM_SHIPPING_lte: int | None = None
    delta30_NEW_FBM_SHIPPING_gte: int | None = None
    delta30_PRIME_EXCL_lte: int | None = None
    delta30_PRIME_EXCL_gte: int | None = None
    delta30_RATING_lte: int | None = None
    delta30_RATING_gte: int | None = None
    delta30_REFURBISHED_lte: int | None = None
    delta30_REFURBISHED_gte: int | None = None
    delta30_REFURBISHED_SHIPPING_lte: int | None = None
    delta30_REFURBISHED_SHIPPING_gte: int | None = None
    delta30_RENT_lte: int | None = None
    delta30_RENT_gte: int | None = None
    delta30_SALES_lte: int | None = None
    delta30_SALES_gte: int | None = None
    delta30_TRADE_IN_lte: int | None = None
    delta30_TRADE_IN_gte: int | None = None
    delta30_USED_lte: int | None = None
    delta30_USED_gte: int | None = None
    delta30_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    delta30_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    delta30_USED_GOOD_SHIPPING_lte: int | None = None
    delta30_USED_GOOD_SHIPPING_gte: int | None = None
    delta30_USED_NEW_SHIPPING_lte: int | None = None
    delta30_USED_NEW_SHIPPING_gte: int | None = None
    delta30_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    delta30_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    delta30_WAREHOUSE_lte: int | None = None
    delta30_WAREHOUSE_gte: int | None = None
    delta7_AMAZON_lte: int | None = None
    delta7_AMAZON_gte: int | None = None
    delta7_BUY_BOX_SHIPPING_lte: int | None = None
    delta7_BUY_BOX_SHIPPING_gte: int | None = None
    delta7_BUY_BOX_USED_SHIPPING_lte: int | None = None
    delta7_BUY_BOX_USED_SHIPPING_gte: int | None = None
    delta7_COLLECTIBLE_lte: int | None = None
    delta7_COLLECTIBLE_gte: int | None = None
    delta7_COUNT_COLLECTIBLE_lte: int | None = None
    delta7_COUNT_COLLECTIBLE_gte: int | None = None
    delta7_COUNT_NEW_lte: int | None = None
    delta7_COUNT_NEW_gte: int | None = None
    delta7_COUNT_REFURBISHED_lte: int | None = None
    delta7_COUNT_REFURBISHED_gte: int | None = None
    delta7_COUNT_REVIEWS_lte: int | None = None
    delta7_COUNT_REVIEWS_gte: int | None = None
    delta7_COUNT_USED_lte: int | None = None
    delta7_COUNT_USED_gte: int | None = None
    delta7_EBAY_NEW_SHIPPING_lte: int | None = None
    delta7_EBAY_NEW_SHIPPING_gte: int | None = None
    delta7_EBAY_USED_SHIPPING_lte: int | None = None
    delta7_EBAY_USED_SHIPPING_gte: int | None = None
    delta7_LIGHTNING_DEAL_lte: int | None = None
    delta7_LIGHTNING_DEAL_gte: int | None = None
    delta7_LISTPRICE_lte: int | None = None
    delta7_LISTPRICE_gte: int | None = None
    delta7_NEW_lte: int | None = None
    delta7_NEW_gte: int | None = None
    delta7_NEW_FBA_lte: int | None = None
    delta7_NEW_FBA_gte: int | None = None
    delta7_NEW_FBM_SHIPPING_lte: int | None = None
    delta7_NEW_FBM_SHIPPING_gte: int | None = None
    delta7_PRIME_EXCL_lte: int | None = None
    delta7_PRIME_EXCL_gte: int | None = None
    delta7_RATING_lte: int | None = None
    delta7_RATING_gte: int | None = None
    delta7_REFURBISHED_lte: int | None = None
    delta7_REFURBISHED_gte: int | None = None
    delta7_REFURBISHED_SHIPPING_lte: int | None = None
    delta7_REFURBISHED_SHIPPING_gte: int | None = None
    delta7_RENT_lte: int | None = None
    delta7_RENT_gte: int | None = None
    delta7_SALES_lte: int | None = None
    delta7_SALES_gte: int | None = None
    delta7_TRADE_IN_lte: int | None = None
    delta7_TRADE_IN_gte: int | None = None
    delta7_USED_lte: int | None = None
    delta7_USED_gte: int | None = None
    delta7_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    delta7_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    delta7_USED_GOOD_SHIPPING_lte: int | None = None
    delta7_USED_GOOD_SHIPPING_gte: int | None = None
    delta7_USED_NEW_SHIPPING_lte: int | None = None
    delta7_USED_NEW_SHIPPING_gte: int | None = None
    delta7_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    delta7_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    delta7_WAREHOUSE_lte: int | None = None
    delta7_WAREHOUSE_gte: int | None = None
    delta90_AMAZON_lte: int | None = None
    delta90_AMAZON_gte: int | None = None
    delta90_BUY_BOX_SHIPPING_lte: int | None = None
    delta90_BUY_BOX_SHIPPING_gte: int | None = None
    delta90_BUY_BOX_USED_SHIPPING_lte: int | None = None
    delta90_BUY_BOX_USED_SHIPPING_gte: int | None = None
    delta90_COLLECTIBLE_lte: int | None = None
    delta90_COLLECTIBLE_gte: int | None = None
    delta90_COUNT_COLLECTIBLE_lte: int | None = None
    delta90_COUNT_COLLECTIBLE_gte: int | None = None
    delta90_COUNT_NEW_lte: int | None = None
    delta90_COUNT_NEW_gte: int | None = None
    delta90_COUNT_REFURBISHED_lte: int | None = None
    delta90_COUNT_REFURBISHED_gte: int | None = None
    delta90_COUNT_REVIEWS_lte: int | None = None
    delta90_COUNT_REVIEWS_gte: int | None = None
    delta90_COUNT_USED_lte: int | None = None
    delta90_COUNT_USED_gte: int | None = None
    delta90_EBAY_NEW_SHIPPING_lte: int | None = None
    delta90_EBAY_NEW_SHIPPING_gte: int | None = None
    delta90_EBAY_USED_SHIPPING_lte: int | None = None
    delta90_EBAY_USED_SHIPPING_gte: int | None = None
    delta90_LIGHTNING_DEAL_lte: int | None = None
    delta90_LIGHTNING_DEAL_gte: int | None = None
    delta90_LISTPRICE_lte: int | None = None
    delta90_LISTPRICE_gte: int | None = None
    delta90_NEW_lte: int | None = None
    delta90_NEW_gte: int | None = None
    delta90_NEW_FBA_lte: int | None = None
    delta90_NEW_FBA_gte: int | None = None
    delta90_NEW_FBM_SHIPPING_lte: int | None = None
    delta90_NEW_FBM_SHIPPING_gte: int | None = None
    delta90_PRIME_EXCL_lte: int | None = None
    delta90_PRIME_EXCL_gte: int | None = None
    delta90_RATING_lte: int | None = None
    delta90_RATING_gte: int | None = None
    delta90_REFURBISHED_lte: int | None = None
    delta90_REFURBISHED_gte: int | None = None
    delta90_REFURBISHED_SHIPPING_lte: int | None = None
    delta90_REFURBISHED_SHIPPING_gte: int | None = None
    delta90_RENT_lte: int | None = None
    delta90_RENT_gte: int | None = None
    delta90_SALES_lte: int | None = None
    delta90_SALES_gte: int | None = None
    delta90_TRADE_IN_lte: int | None = None
    delta90_TRADE_IN_gte: int | None = None
    delta90_USED_lte: int | None = None
    delta90_USED_gte: int | None = None
    delta90_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    delta90_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    delta90_USED_GOOD_SHIPPING_lte: int | None = None
    delta90_USED_GOOD_SHIPPING_gte: int | None = None
    delta90_USED_NEW_SHIPPING_lte: int | None = None
    delta90_USED_NEW_SHIPPING_gte: int | None = None
    delta90_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    delta90_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    delta90_WAREHOUSE_lte: int | None = None
    delta90_WAREHOUSE_gte: int | None = None
    deltaLast_AMAZON_lte: int | None = None
    deltaLast_AMAZON_gte: int | None = None
    deltaLast_BUY_BOX_SHIPPING_lte: int | None = None
    deltaLast_BUY_BOX_SHIPPING_gte: int | None = None
    deltaLast_BUY_BOX_USED_SHIPPING_lte: int | None = None
    deltaLast_BUY_BOX_USED_SHIPPING_gte: int | None = None
    deltaLast_COLLECTIBLE_lte: int | None = None
    deltaLast_COLLECTIBLE_gte: int | None = None
    deltaLast_COUNT_COLLECTIBLE_lte: int | None = None
    deltaLast_COUNT_COLLECTIBLE_gte: int | None = None
    deltaLast_COUNT_NEW_lte: int | None = None
    deltaLast_COUNT_NEW_gte: int | None = None
    deltaLast_COUNT_REFURBISHED_lte: int | None = None
    deltaLast_COUNT_REFURBISHED_gte: int | None = None
    deltaLast_COUNT_REVIEWS_lte: int | None = None
    deltaLast_COUNT_REVIEWS_gte: int | None = None
    deltaLast_COUNT_USED_lte: int | None = None
    deltaLast_COUNT_USED_gte: int | None = None
    deltaLast_EBAY_NEW_SHIPPING_lte: int | None = None
    deltaLast_EBAY_NEW_SHIPPING_gte: int | None = None
    deltaLast_EBAY_USED_SHIPPING_lte: int | None = None
    deltaLast_EBAY_USED_SHIPPING_gte: int | None = None
    deltaLast_LIGHTNING_DEAL_lte: int | None = None
    deltaLast_LIGHTNING_DEAL_gte: int | None = None
    deltaLast_LISTPRICE_lte: int | None = None
    deltaLast_LISTPRICE_gte: int | None = None
    deltaLast_NEW_lte: int | None = None
    deltaLast_NEW_gte: int | None = None
    deltaLast_NEW_FBA_lte: int | None = None
    deltaLast_NEW_FBA_gte: int | None = None
    deltaLast_NEW_FBM_SHIPPING_lte: int | None = None
    deltaLast_NEW_FBM_SHIPPING_gte: int | None = None
    deltaLast_PRIME_EXCL_lte: int | None = None
    deltaLast_PRIME_EXCL_gte: int | None = None
    deltaLast_RATING_lte: int | None = None
    deltaLast_RATING_gte: int | None = None
    deltaLast_REFURBISHED_lte: int | None = None
    deltaLast_REFURBISHED_gte: int | None = None
    deltaLast_REFURBISHED_SHIPPING_lte: int | None = None
    deltaLast_REFURBISHED_SHIPPING_gte: int | None = None
    deltaLast_RENT_lte: int | None = None
    deltaLast_RENT_gte: int | None = None
    deltaLast_SALES_lte: int | None = None
    deltaLast_SALES_gte: int | None = None
    deltaLast_TRADE_IN_lte: int | None = None
    deltaLast_TRADE_IN_gte: int | None = None
    deltaLast_USED_lte: int | None = None
    deltaLast_USED_gte: int | None = None
    deltaLast_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    deltaLast_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    deltaLast_USED_GOOD_SHIPPING_lte: int | None = None
    deltaLast_USED_GOOD_SHIPPING_gte: int | None = None
    deltaLast_USED_NEW_SHIPPING_lte: int | None = None
    deltaLast_USED_NEW_SHIPPING_gte: int | None = None
    deltaLast_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    deltaLast_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    deltaLast_WAREHOUSE_lte: int | None = None
    deltaLast_WAREHOUSE_gte: int | None = None
    deltaPercent1_AMAZON_lte: int | None = None
    deltaPercent1_AMAZON_gte: int | None = None
    deltaPercent1_BUY_BOX_SHIPPING_lte: int | None = None
    deltaPercent1_BUY_BOX_SHIPPING_gte: int | None = None
    deltaPercent1_BUY_BOX_USED_SHIPPING_lte: int | None = None
    deltaPercent1_BUY_BOX_USED_SHIPPING_gte: int | None = None
    deltaPercent1_COLLECTIBLE_lte: int | None = None
    deltaPercent1_COLLECTIBLE_gte: int | None = None
    deltaPercent1_COUNT_COLLECTIBLE_lte: int | None = None
    deltaPercent1_COUNT_COLLECTIBLE_gte: int | None = None
    deltaPercent1_COUNT_NEW_lte: int | None = None
    deltaPercent1_COUNT_NEW_gte: int | None = None
    deltaPercent1_COUNT_REFURBISHED_lte: int | None = None
    deltaPercent1_COUNT_REFURBISHED_gte: int | None = None
    deltaPercent1_COUNT_REVIEWS_lte: int | None = None
    deltaPercent1_COUNT_REVIEWS_gte: int | None = None
    deltaPercent1_COUNT_USED_lte: int | None = None
    deltaPercent1_COUNT_USED_gte: int | None = None
    deltaPercent1_EBAY_NEW_SHIPPING_lte: int | None = None
    deltaPercent1_EBAY_NEW_SHIPPING_gte: int | None = None
    deltaPercent1_EBAY_USED_SHIPPING_lte: int | None = None
    deltaPercent1_EBAY_USED_SHIPPING_gte: int | None = None
    deltaPercent1_LIGHTNING_DEAL_lte: int | None = None
    deltaPercent1_LIGHTNING_DEAL_gte: int | None = None
    deltaPercent1_LISTPRICE_lte: int | None = None
    deltaPercent1_LISTPRICE_gte: int | None = None
    deltaPercent1_NEW_lte: int | None = None
    deltaPercent1_NEW_gte: int | None = None
    deltaPercent1_NEW_FBA_lte: int | None = None
    deltaPercent1_NEW_FBA_gte: int | None = None
    deltaPercent1_NEW_FBM_SHIPPING_lte: int | None = None
    deltaPercent1_NEW_FBM_SHIPPING_gte: int | None = None
    deltaPercent1_PRIME_EXCL_lte: int | None = None
    deltaPercent1_PRIME_EXCL_gte: int | None = None
    deltaPercent1_RATING_lte: int | None = None
    deltaPercent1_RATING_gte: int | None = None
    deltaPercent1_REFURBISHED_lte: int | None = None
    deltaPercent1_REFURBISHED_gte: int | None = None
    deltaPercent1_REFURBISHED_SHIPPING_lte: int | None = None
    deltaPercent1_REFURBISHED_SHIPPING_gte: int | None = None
    deltaPercent1_RENT_lte: int | None = None
    deltaPercent1_RENT_gte: int | None = None
    deltaPercent1_SALES_lte: int | None = None
    deltaPercent1_SALES_gte: int | None = None
    deltaPercent1_TRADE_IN_lte: int | None = None
    deltaPercent1_TRADE_IN_gte: int | None = None
    deltaPercent1_USED_lte: int | None = None
    deltaPercent1_USED_gte: int | None = None
    deltaPercent1_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    deltaPercent1_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    deltaPercent1_USED_GOOD_SHIPPING_lte: int | None = None
    deltaPercent1_USED_GOOD_SHIPPING_gte: int | None = None
    deltaPercent1_USED_NEW_SHIPPING_lte: int | None = None
    deltaPercent1_USED_NEW_SHIPPING_gte: int | None = None
    deltaPercent1_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    deltaPercent1_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    deltaPercent1_WAREHOUSE_lte: int | None = None
    deltaPercent1_WAREHOUSE_gte: int | None = None
    deltaPercent30_AMAZON_lte: int | None = None
    deltaPercent30_AMAZON_gte: int | None = None
    deltaPercent30_BUY_BOX_SHIPPING_lte: int | None = None
    deltaPercent30_BUY_BOX_SHIPPING_gte: int | None = None
    deltaPercent30_BUY_BOX_USED_SHIPPING_lte: int | None = None
    deltaPercent30_BUY_BOX_USED_SHIPPING_gte: int | None = None
    deltaPercent30_COLLECTIBLE_lte: int | None = None
    deltaPercent30_COLLECTIBLE_gte: int | None = None
    deltaPercent30_COUNT_COLLECTIBLE_lte: int | None = None
    deltaPercent30_COUNT_COLLECTIBLE_gte: int | None = None
    deltaPercent30_COUNT_NEW_lte: int | None = None
    deltaPercent30_COUNT_NEW_gte: int | None = None
    deltaPercent30_COUNT_REFURBISHED_lte: int | None = None
    deltaPercent30_COUNT_REFURBISHED_gte: int | None = None
    deltaPercent30_COUNT_REVIEWS_lte: int | None = None
    deltaPercent30_COUNT_REVIEWS_gte: int | None = None
    deltaPercent30_COUNT_USED_lte: int | None = None
    deltaPercent30_COUNT_USED_gte: int | None = None
    deltaPercent30_EBAY_NEW_SHIPPING_lte: int | None = None
    deltaPercent30_EBAY_NEW_SHIPPING_gte: int | None = None
    deltaPercent30_EBAY_USED_SHIPPING_lte: int | None = None
    deltaPercent30_EBAY_USED_SHIPPING_gte: int | None = None
    deltaPercent30_LIGHTNING_DEAL_lte: int | None = None
    deltaPercent30_LIGHTNING_DEAL_gte: int | None = None
    deltaPercent30_LISTPRICE_lte: int | None = None
    deltaPercent30_LISTPRICE_gte: int | None = None
    deltaPercent30_NEW_lte: int | None = None
    deltaPercent30_NEW_gte: int | None = None
    deltaPercent30_NEW_FBA_lte: int | None = None
    deltaPercent30_NEW_FBA_gte: int | None = None
    deltaPercent30_NEW_FBM_SHIPPING_lte: int | None = None
    deltaPercent30_NEW_FBM_SHIPPING_gte: int | None = None
    deltaPercent30_PRIME_EXCL_lte: int | None = None
    deltaPercent30_PRIME_EXCL_gte: int | None = None
    deltaPercent30_RATING_lte: int | None = None
    deltaPercent30_RATING_gte: int | None = None
    deltaPercent30_REFURBISHED_lte: int | None = None
    deltaPercent30_REFURBISHED_gte: int | None = None
    deltaPercent30_REFURBISHED_SHIPPING_lte: int | None = None
    deltaPercent30_REFURBISHED_SHIPPING_gte: int | None = None
    deltaPercent30_RENT_lte: int | None = None
    deltaPercent30_RENT_gte: int | None = None
    deltaPercent30_SALES_lte: int | None = None
    deltaPercent30_SALES_gte: int | None = None
    deltaPercent30_TRADE_IN_lte: int | None = None
    deltaPercent30_TRADE_IN_gte: int | None = None
    deltaPercent30_USED_lte: int | None = None
    deltaPercent30_USED_gte: int | None = None
    deltaPercent30_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    deltaPercent30_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    deltaPercent30_USED_GOOD_SHIPPING_lte: int | None = None
    deltaPercent30_USED_GOOD_SHIPPING_gte: int | None = None
    deltaPercent30_USED_NEW_SHIPPING_lte: int | None = None
    deltaPercent30_USED_NEW_SHIPPING_gte: int | None = None
    deltaPercent30_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    deltaPercent30_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    deltaPercent30_WAREHOUSE_lte: int | None = None
    deltaPercent30_WAREHOUSE_gte: int | None = None
    deltaPercent7_AMAZON_lte: int | None = None
    deltaPercent7_AMAZON_gte: int | None = None
    deltaPercent7_BUY_BOX_SHIPPING_lte: int | None = None
    deltaPercent7_BUY_BOX_SHIPPING_gte: int | None = None
    deltaPercent7_BUY_BOX_USED_SHIPPING_lte: int | None = None
    deltaPercent7_BUY_BOX_USED_SHIPPING_gte: int | None = None
    deltaPercent7_COLLECTIBLE_lte: int | None = None
    deltaPercent7_COLLECTIBLE_gte: int | None = None
    deltaPercent7_COUNT_COLLECTIBLE_lte: int | None = None
    deltaPercent7_COUNT_COLLECTIBLE_gte: int | None = None
    deltaPercent7_COUNT_NEW_lte: int | None = None
    deltaPercent7_COUNT_NEW_gte: int | None = None
    deltaPercent7_COUNT_REFURBISHED_lte: int | None = None
    deltaPercent7_COUNT_REFURBISHED_gte: int | None = None
    deltaPercent7_COUNT_REVIEWS_lte: int | None = None
    deltaPercent7_COUNT_REVIEWS_gte: int | None = None
    deltaPercent7_COUNT_USED_lte: int | None = None
    deltaPercent7_COUNT_USED_gte: int | None = None
    deltaPercent7_EBAY_NEW_SHIPPING_lte: int | None = None
    deltaPercent7_EBAY_NEW_SHIPPING_gte: int | None = None
    deltaPercent7_EBAY_USED_SHIPPING_lte: int | None = None
    deltaPercent7_EBAY_USED_SHIPPING_gte: int | None = None
    deltaPercent7_LIGHTNING_DEAL_lte: int | None = None
    deltaPercent7_LIGHTNING_DEAL_gte: int | None = None
    deltaPercent7_LISTPRICE_lte: int | None = None
    deltaPercent7_LISTPRICE_gte: int | None = None
    deltaPercent7_NEW_lte: int | None = None
    deltaPercent7_NEW_gte: int | None = None
    deltaPercent7_NEW_FBA_lte: int | None = None
    deltaPercent7_NEW_FBA_gte: int | None = None
    deltaPercent7_NEW_FBM_SHIPPING_lte: int | None = None
    deltaPercent7_NEW_FBM_SHIPPING_gte: int | None = None
    deltaPercent7_PRIME_EXCL_lte: int | None = None
    deltaPercent7_PRIME_EXCL_gte: int | None = None
    deltaPercent7_RATING_lte: int | None = None
    deltaPercent7_RATING_gte: int | None = None
    deltaPercent7_REFURBISHED_lte: int | None = None
    deltaPercent7_REFURBISHED_gte: int | None = None
    deltaPercent7_REFURBISHED_SHIPPING_lte: int | None = None
    deltaPercent7_REFURBISHED_SHIPPING_gte: int | None = None
    deltaPercent7_RENT_lte: int | None = None
    deltaPercent7_RENT_gte: int | None = None
    deltaPercent7_SALES_lte: int | None = None
    deltaPercent7_SALES_gte: int | None = None
    deltaPercent7_TRADE_IN_lte: int | None = None
    deltaPercent7_TRADE_IN_gte: int | None = None
    deltaPercent7_USED_lte: int | None = None
    deltaPercent7_USED_gte: int | None = None
    deltaPercent7_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    deltaPercent7_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    deltaPercent7_USED_GOOD_SHIPPING_lte: int | None = None
    deltaPercent7_USED_GOOD_SHIPPING_gte: int | None = None
    deltaPercent7_USED_NEW_SHIPPING_lte: int | None = None
    deltaPercent7_USED_NEW_SHIPPING_gte: int | None = None
    deltaPercent7_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    deltaPercent7_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    deltaPercent7_WAREHOUSE_lte: int | None = None
    deltaPercent7_WAREHOUSE_gte: int | None = None
    deltaPercent90_AMAZON_lte: int | None = None
    deltaPercent90_AMAZON_gte: int | None = None
    deltaPercent90_BUY_BOX_SHIPPING_lte: int | None = None
    deltaPercent90_BUY_BOX_SHIPPING_gte: int | None = None
    deltaPercent90_BUY_BOX_USED_SHIPPING_lte: int | None = None
    deltaPercent90_BUY_BOX_USED_SHIPPING_gte: int | None = None
    deltaPercent90_COLLECTIBLE_lte: int | None = None
    deltaPercent90_COLLECTIBLE_gte: int | None = None
    deltaPercent90_COUNT_COLLECTIBLE_lte: int | None = None
    deltaPercent90_COUNT_COLLECTIBLE_gte: int | None = None
    deltaPercent90_COUNT_NEW_lte: int | None = None
    deltaPercent90_COUNT_NEW_gte: int | None = None
    deltaPercent90_COUNT_REFURBISHED_lte: int | None = None
    deltaPercent90_COUNT_REFURBISHED_gte: int | None = None
    deltaPercent90_COUNT_REVIEWS_lte: int | None = None
    deltaPercent90_COUNT_REVIEWS_gte: int | None = None
    deltaPercent90_COUNT_USED_lte: int | None = None
    deltaPercent90_COUNT_USED_gte: int | None = None
    deltaPercent90_EBAY_NEW_SHIPPING_lte: int | None = None
    deltaPercent90_EBAY_NEW_SHIPPING_gte: int | None = None
    deltaPercent90_EBAY_USED_SHIPPING_lte: int | None = None
    deltaPercent90_EBAY_USED_SHIPPING_gte: int | None = None
    deltaPercent90_LIGHTNING_DEAL_lte: int | None = None
    deltaPercent90_LIGHTNING_DEAL_gte: int | None = None
    deltaPercent90_LISTPRICE_lte: int | None = None
    deltaPercent90_LISTPRICE_gte: int | None = None
    deltaPercent90_NEW_lte: int | None = None
    deltaPercent90_NEW_gte: int | None = None
    deltaPercent90_NEW_FBA_lte: int | None = None
    deltaPercent90_NEW_FBA_gte: int | None = None
    deltaPercent90_NEW_FBM_SHIPPING_lte: int | None = None
    deltaPercent90_NEW_FBM_SHIPPING_gte: int | None = None
    deltaPercent90_PRIME_EXCL_lte: int | None = None
    deltaPercent90_PRIME_EXCL_gte: int | None = None
    deltaPercent90_RATING_lte: int | None = None
    deltaPercent90_RATING_gte: int | None = None
    deltaPercent90_REFURBISHED_lte: int | None = None
    deltaPercent90_REFURBISHED_gte: int | None = None
    deltaPercent90_REFURBISHED_SHIPPING_lte: int | None = None
    deltaPercent90_REFURBISHED_SHIPPING_gte: int | None = None
    deltaPercent90_RENT_lte: int | None = None
    deltaPercent90_RENT_gte: int | None = None
    deltaPercent90_SALES_lte: int | None = None
    deltaPercent90_SALES_gte: int | None = None
    deltaPercent90_TRADE_IN_lte: int | None = None
    deltaPercent90_TRADE_IN_gte: int | None = None
    deltaPercent90_USED_lte: int | None = None
    deltaPercent90_USED_gte: int | None = None
    deltaPercent90_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    deltaPercent90_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    deltaPercent90_USED_GOOD_SHIPPING_lte: int | None = None
    deltaPercent90_USED_GOOD_SHIPPING_gte: int | None = None
    deltaPercent90_USED_NEW_SHIPPING_lte: int | None = None
    deltaPercent90_USED_NEW_SHIPPING_gte: int | None = None
    deltaPercent90_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    deltaPercent90_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    deltaPercent90_WAREHOUSE_lte: int | None = None
    deltaPercent90_WAREHOUSE_gte: int | None = None
    edition: list[str | None] | None = None
    fbaFees_lte: int | None = None
    fbaFees_gte: int | None = None
    format: list[str | None] | None = None
    genre: list[str | None] | None = None
    hasParentASIN: bool | None = None
    hasReviews: bool | None = None
    isAdultProduct: bool | None = None
    isEligibleForSuperSaverShipping: bool | None = None
    isEligibleForTradeIn: bool | None = None
    isHighestOffer: bool | None = None
    isLowestOffer: bool | None = None
    isLowest_AMAZON: bool | None = None
    isLowest_BUY_BOX_SHIPPING: bool | None = None
    isLowest_BUY_BOX_USED_SHIPPING: bool | None = None
    isLowest_COLLECTIBLE: bool | None = None
    isLowest_COUNT_COLLECTIBLE: bool | None = None
    isLowest_COUNT_NEW: bool | None = None
    isLowest_COUNT_REFURBISHED: bool | None = None
    isLowest_COUNT_REVIEWS: bool | None = None
    isLowest_COUNT_USED: bool | None = None
    isLowest_EBAY_NEW_SHIPPING: bool | None = None
    isLowest_EBAY_USED_SHIPPING: bool | None = None
    isLowest_LIGHTNING_DEAL: bool | None = None
    isLowest_LISTPRICE: bool | None = None
    isLowest_NEW: bool | None = None
    isLowest_NEW_FBA: bool | None = None
    isLowest_NEW_FBM_SHIPPING: bool | None = None
    isLowest_PRIME_EXCL: bool | None = None
    isLowest_RATING: bool | None = None
    isLowest_REFURBISHED: bool | None = None
    isLowest_REFURBISHED_SHIPPING: bool | None = None
    isLowest_RENT: bool | None = None
    isLowest_SALES: bool | None = None
    isLowest_TRADE_IN: bool | None = None
    isLowest_USED: bool | None = None
    isLowest_USED_ACCEPTABLE_SHIPPING: bool | None = None
    isLowest_USED_GOOD_SHIPPING: bool | None = None
    isLowest_USED_NEW_SHIPPING: bool | None = None
    isLowest_USED_VERY_GOOD_SHIPPING: bool | None = None
    isLowest_WAREHOUSE: bool | None = None
    isPrimeExclusive: bool | None = None
    isSNS: bool | None = None
    itemDimension_lte: int | None = None
    itemDimension_gte: int | None = None
    itemHeight_lte: int | None = None
    itemHeight_gte: int | None = None
    itemLength_lte: int | None = None
    itemLength_gte: int | None = None
    itemWeight_lte: int | None = None
    itemWeight_gte: int | None = None
    itemWidth_lte: int | None = None
    itemWidth_gte: int | None = None
    label: list[str | None] | None = None
    languages: list[str | None] | None = None
    lastOffersUpdate_lte: int | None = None
    lastOffersUpdate_gte: int | None = None
    lastPriceChange_lte: int | None = None
    lastPriceChange_gte: int | None = None
    lastPriceChange_AMAZON_lte: int | None = None
    lastPriceChange_AMAZON_gte: int | None = None
    lastPriceChange_NEW_lte: int | None = None
    lastPriceChange_NEW_gte: int | None = None
    lastPriceChange_USED_lte: int | None = None
    lastPriceChange_USED_gte: int | None = None
    lastPriceChange_SALES_lte: int | None = None
    lastPriceChange_SALES_gte: int | None = None
    lastPriceChange_LISTPRICE_lte: int | None = None
    lastPriceChange_LISTPRICE_gte: int | None = None
    lastPriceChange_COLLECTIBLE_lte: int | None = None
    lastPriceChange_COLLECTIBLE_gte: int | None = None
    lastPriceChange_REFURBISHED_lte: int | None = None
    lastPriceChange_REFURBISHED_gte: int | None = None
    lastPriceChange_NEW_FBM_SHIPPING_lte: int | None = None
    lastPriceChange_NEW_FBM_SHIPPING_gte: int | None = None
    lastPriceChange_LIGHTNING_DEAL_lte: int | None = None
    lastPriceChange_LIGHTNING_DEAL_gte: int | None = None
    lastPriceChange_WAREHOUSE_lte: int | None = None
    lastPriceChange_WAREHOUSE_gte: int | None = None
    lastPriceChange_NEW_FBA_lte: int | None = None
    lastPriceChange_NEW_FBA_gte: int | None = None
    lastPriceChange_COUNT_NEW_lte: int | None = None
    lastPriceChange_COUNT_NEW_gte: int | None = None
    lastPriceChange_COUNT_USED_lte: int | None = None
    lastPriceChange_COUNT_USED_gte: int | None = None
    lastPriceChange_COUNT_REFURBISHED_lte: int | None = None
    lastPriceChange_COUNT_REFURBISHED_gte: int | None = None
    lastPriceChange_COUNT_COLLECTIBLE_lte: int | None = None
    lastPriceChange_COUNT_COLLECTIBLE_gte: int | None = None
    lastPriceChange_RATING_lte: int | None = None
    lastPriceChange_RATING_gte: int | None = None
    lastPriceChange_COUNT_REVIEWS_lte: int | None = None
    lastPriceChange_COUNT_REVIEWS_gte: int | None = None
    lastPriceChange_BUY_BOX_SHIPPING_lte: int | None = None
    lastPriceChange_BUY_BOX_SHIPPING_gte: int | None = None
    lastPriceChange_USED_NEW_SHIPPING_lte: int | None = None
    lastPriceChange_USED_NEW_SHIPPING_gte: int | None = None
    lastPriceChange_USED_VERY_GOOD_SHIPPING_lte: int | None = None
    lastPriceChange_USED_VERY_GOOD_SHIPPING_gte: int | None = None
    lastPriceChange_USED_GOOD_SHIPPING_lte: int | None = None
    lastPriceChange_USED_GOOD_SHIPPING_gte: int | None = None
    lastPriceChange_USED_ACCEPTABLE_SHIPPING_lte: int | None = None
    lastPriceChange_USED_ACCEPTABLE_SHIPPING_gte: int | None = None
    lastPriceChange_REFURBISHED_SHIPPING_lte: int | None = None
    lastPriceChange_REFURBISHED_SHIPPING_gte: int | None = None
    lastPriceChange_EBAY_NEW_SHIPPING_lte: int | None = None
    lastPriceChange_EBAY_NEW_SHIPPING_gte: int | None = None
    lastPriceChange_EBAY_USED_SHIPPING_lte: int | None = None
    lastPriceChange_EBAY_USED_SHIPPING_gte: int | None = None
    lastPriceChange_TRADE_IN_lte: int | None = None
    lastPriceChange_TRADE_IN_gte: int | None = None
    lastPriceChange_RENT_lte: int | None = None
    lastPriceChange_RENT_gte: int | None = None
    lastPriceChange_BUY_BOX_USED_SHIPPING_lte: int | None = None
    lastPriceChange_BUY_BOX_USED_SHIPPING_gte: int | None = None
    lastPriceChange_PRIME_EXCL_lte: int | None = None
    lastPriceChange_PRIME_EXCL_gte: int | None = None
    lastRatingUpdate_lte: int | None = None
    lastRatingUpdate_gte: int | None = None
    lastUpdate_lte: int | None = None
    lastUpdate_gte: int | None = None
    lightningEnd_lte: int | None = None
    lightningEnd_gte: int | None = None
    lightningStart_lte: int | None = None
    lightningStart_gte: int | None = None
    listedSince_lte: int | None = None
    listedSince_gte: int | None = None
    manufacturer: list[str | None] | None = None
    model: list[str | None] | None = None
    newPriceIsMAP: bool | None = None
    nextUpdate_lte: int | None = None
    nextUpdate_gte: int | None = None
    numberOfItems_lte: int | None = None
    numberOfItems_gte: int | None = None
    numberOfPages_lte: int | None = None
    numberOfPages_gte: int | None = None
    numberOfTrackings_lte: int | None = None
    numberOfTrackings_gte: int | None = None
    offerCountFBA_lte: int | None = None
    offerCountFBA_gte: int | None = None
    offerCountFBM_lte: int | None = None
    offerCountFBM_gte: int | None = None
    outOfStockPercentage90_BB_lte: int | None = None
    outOfStockPercentage90_BB_gte: int | None = None
    outOfStockPercentage90_BB_USED_lte: int | None = None
    outOfStockPercentage90_BB_USED_gte: int | None = None
    outOfStockPercentage90_NEW_lte: int | None = None
    outOfStockPercentage90_NEW_gte: int | None = None
    outOfStockPercentage90_USED_lte: int | None = None
    outOfStockPercentage90_USED_gte: int | None = None
    outOfStockPercentageInInterval_lte: int | None = None
    outOfStockPercentageInInterval_gte: int | None = None
    packageDimension_lte: int | None = None
    packageDimension_gte: int | None = None
    packageHeight_lte: int | None = None
    packageHeight_gte: int | None = None
    packageLength_lte: int | None = None
    packageLength_gte: int | None = None
    packageQuantity_lte: int | None = None
    packageQuantity_gte: int | None = None
    packageWeight_lte: int | None = None
    packageWeight_gte: int | None = None
    packageWidth_lte: int | None = None
    packageWidth_gte: int | None = None
    partNumber: list[str | None] | None = None
    platform: list[str | None] | None = None
    productGroup: list[str | None] | None = None
    productType: list[int | None] | None = None
    publicationDate_lte: int | None = None
    publicationDate_gte: int | None = None
    publisher: list[str | None] | None = None
    releaseDate_lte: int | None = None
    releaseDate_gte: int | None = None
    rootCategory: list[str | None] | None = None
    salesRankDrops180_lte: int | None = None
    salesRankDrops180_gte: int | None = None
    salesRankDrops30_lte: int | None = None
    salesRankDrops30_gte: int | None = None
    salesRankDrops365_lte: int | None = None
    salesRankDrops365_gte: int | None = None
    salesRankDrops90_lte: int | None = None
    salesRankDrops90_gte: int | None = None
    salesRankReference: int | None = None
    salesRankTopPct_lte: int | None = None
    salesRankTopPct_gte: int | None = None
    sellerIds: list[str | None] | None = None
    sellerIdsLowestFBA: list[str | None] | None = None
    sellerIdsLowestFBM: list[str | None] | None = None
    size: list[str | None] | None = None
    studio: list[str | None] | None = None
    title: str | None = None
    title_flag: str | None = None
    totalOfferCount_lte: int | None = None
    totalOfferCount_gte: int | None = None
    trackingSince_lte: int | None = None
    trackingSince_gte: int | None = None
    monthlySold_lte: int | None = None
    monthlySold_gte: int | None = None
    buyBoxIsPreorder: bool | None = None
    buyBoxIsBackorder: bool | None = None
    buyBoxIsPrimeExclusive: bool | None = None
    buyBoxIsPrimeEligible: bool | None = None
    type: list[str | None] | None = None
    warehouseCondition: list[int | None] | None = None
    singleVariation: bool | None = None
    outOfStockPercentage90_lte: int | None = None
    outOfStockPercentage90_gte: int | None = None
    variationCount_lte: int | None = None
    variationCount_gte: int | None = None
    imageCount_lte: int | None = None
    imageCount_gte: int | None = None
    buyBoxStatsAmazon30_lte: int | None = None
    buyBoxStatsAmazon30_gte: int | None = None
    buyBoxStatsAmazon90_lte: int | None = None
    buyBoxStatsAmazon90_gte: int | None = None
    buyBoxStatsAmazon180_lte: int | None = None
    buyBoxStatsAmazon180_gte: int | None = None
    buyBoxStatsAmazon365_lte: int | None = None
    buyBoxStatsAmazon365_gte: int | None = None
    buyBoxStatsTopSeller30_lte: int | None = None
    buyBoxStatsTopSeller30_gte: int | None = None
    buyBoxStatsTopSeller90_lte: int | None = None
    buyBoxStatsTopSeller90_gte: int | None = None
    buyBoxStatsTopSeller180_lte: int | None = None
    buyBoxStatsTopSeller180_gte: int | None = None
    buyBoxStatsTopSeller365_lte: int | None = None
    buyBoxStatsTopSeller365_gte: int | None = None
    buyBoxStatsSellerCount30_lte: int | None = None
    buyBoxStatsSellerCount30_gte: int | None = None
    buyBoxStatsSellerCount90_lte: int | None = None
    buyBoxStatsSellerCount90_gte: int | None = None
    buyBoxStatsSellerCount180_lte: int | None = None
    buyBoxStatsSellerCount180_gte: int | None = None
    buyBoxStatsSellerCount365_lte: int | None = None
    buyBoxStatsSellerCount365_gte: int | None = None
    isHazMat: bool | None = None
    isHeatSensitive: bool | None = None
    buyBoxStandardDeviation30_lte: int | None = None
    buyBoxStandardDeviation30_gte: int | None = None
    buyBoxStandardDeviation90_lte: int | None = None
    buyBoxStandardDeviation90_gte: int | None = None
    buyBoxStandardDeviation365_lte: int | None = None
    buyBoxStandardDeviation365_gte: int | None = None
    flipability30_lte: int | None = None
    flipability30_gte: int | None = None
    flipability90_lte: int | None = None
    flipability90_gte: int | None = None
    flipability365_lte: int | None = None
    flipability365_gte: int | None = None
    itemTypeKeyword: list[str | None] | None = None
    targetAudienceKeyword: list[str | None] | None = None
    itemForm: list[str | None] | None = None
    scent: str | None = None
    unitType: str | None = None
    unitValue_lte: float | None = None
    unitValue_gte: float | None = None
    pattern: str | None = None
    batteriesRequired: bool | None = None
    batteriesIncluded: bool | None = None
    style: str | None = None
    material: str | None = None
    lastBusinessDiscountUpdate_lte: int | None = None
    lastBusinessDiscountUpdate_gte: int | None = None
    businessDiscount_lte: int | None = None
    businessDiscount_gte: int | None = None
    activeIngredients: list[str | None] | None = None
    specialIngredients: list[str | None] | None = None
    isMerchOnDemand: bool | None = None
    hasMainVideo: bool | None = None
    hasAPlus: bool | None = None
    hasAPlusFromManufacturer: bool | None = None
    videoCount_lte: int | None = None
    videoCount_gte: int | None = None
    brandStoreName: list[str | None] | None = None
    brandStoreUrlName: list[str | None] | None = None
    returnRate: list[int | None] | None = None
    deltaPercent90_monthlySold_lte: int | None = None
    deltaPercent90_monthlySold_gte: int | None = None
    outOfStockCountAmazon30_lte: int | None = None
    outOfStockCountAmazon30_gte: int | None = None
    outOfStockCountAmazon90_lte: int | None = None
    outOfStockCountAmazon90_gte: int | None = None
    variationReviewCount_lte: int | None = None
    variationReviewCount_gte: int | None = None
    variationRatingCount_lte: int | None = None
    variationRatingCount_gte: int | None = None
    websiteDisplayGroupName: list[str | None] | None = None
    websiteDisplayGroup: list[str | None] | None = None
    availabilityAmazonMinDelayInDays_lte: int | None = None
    availabilityAmazonMinDelayInDays_gte: int | None = None
    blackList: list[int | None] | None = None
    isDeal: bool | None = None
    launchpad: bool | None = None
    historicalSellerIds: list[str | None] | None = None
    buyBoxShippingCountry: list[str | None] | None = None
    sellerIdsFBA: list[str | None] | None = None
    sellerIdsFBM: list[str | None] | None = None
    buyBoxStatsTopSellerId30: list[str | None] | None = None
    buyBoxStatsTopSellerId90: list[str | None] | None = None
    buyBoxStatsTopSellerId180: list[str | None] | None = None
    buyBoxStatsTopSellerId365: list[str | None] | None = None
    buyBoxEligibleOfferCountsNewFBA_lte: int | None = None
    buyBoxEligibleOfferCountsNewFBA_gte: int | None = None
    buyBoxEligibleOfferCountsNewFBM_lte: int | None = None
    buyBoxEligibleOfferCountsNewFBM_gte: int | None = None
    buyBoxEligibleOfferCountsUsedFBA_lte: int | None = None
    buyBoxEligibleOfferCountsUsedFBA_gte: int | None = None
    buyBoxEligibleOfferCountsUsedFBM_lte: int | None = None
    buyBoxEligibleOfferCountsUsedFBM_gte: int | None = None
    srAvg000_gte: int | None = None
    srAvg001_gte: int | None = None
    srAvg002_gte: int | None = None
    srAvg003_gte: int | None = None
    srAvg004_gte: int | None = None
    srAvg005_gte: int | None = None
    srAvg006_gte: int | None = None
    srAvg007_gte: int | None = None
    srAvg008_gte: int | None = None
    srAvg009_gte: int | None = None
    srAvg010_gte: int | None = None
    srAvg011_gte: int | None = None
    srAvg100_gte: int | None = None
    srAvg101_gte: int | None = None
    srAvg102_gte: int | None = None
    srAvg103_gte: int | None = None
    srAvg104_gte: int | None = None
    srAvg105_gte: int | None = None
    srAvg106_gte: int | None = None
    srAvg107_gte: int | None = None
    srAvg108_gte: int | None = None
    srAvg109_gte: int | None = None
    srAvg110_gte: int | None = None
    srAvg111_gte: int | None = None
    srAvg200_gte: int | None = None
    srAvg201_gte: int | None = None
    srAvg202_gte: int | None = None
    srAvg203_gte: int | None = None
    srAvg204_gte: int | None = None
    srAvg205_gte: int | None = None
    srAvg206_gte: int | None = None
    srAvg207_gte: int | None = None
    srAvg208_gte: int | None = None
    srAvg209_gte: int | None = None
    srAvg210_gte: int | None = None
    srAvg211_gte: int | None = None
    srAvg000_lte: int | None = None
    srAvg001_lte: int | None = None
    srAvg002_lte: int | None = None
    srAvg003_lte: int | None = None
    srAvg004_lte: int | None = None
    srAvg005_lte: int | None = None
    srAvg006_lte: int | None = None
    srAvg007_lte: int | None = None
    srAvg008_lte: int | None = None
    srAvg009_lte: int | None = None
    srAvg010_lte: int | None = None
    srAvg011_lte: int | None = None
    srAvg100_lte: int | None = None
    srAvg101_lte: int | None = None
    srAvg102_lte: int | None = None
    srAvg103_lte: int | None = None
    srAvg104_lte: int | None = None
    srAvg105_lte: int | None = None
    srAvg106_lte: int | None = None
    srAvg107_lte: int | None = None
    srAvg108_lte: int | None = None
    srAvg109_lte: int | None = None
    srAvg110_lte: int | None = None
    srAvg111_lte: int | None = None
    srAvg200_lte: int | None = None
    srAvg201_lte: int | None = None
    srAvg202_lte: int | None = None
    srAvg203_lte: int | None = None
    srAvg204_lte: int | None = None
    srAvg205_lte: int | None = None
    srAvg206_lte: int | None = None
    srAvg207_lte: int | None = None
    srAvg208_lte: int | None = None
    srAvg209_lte: int | None = None
    srAvg210_lte: int | None = None
    srAvg211_lte: int | None = None
    minMatch: dict[str, int | None] | None = None
    sort: list[list[str | None] | None] | None = None
    perPage: int | None = None
    page: int | None = None


class PromotionObject(KeepaBackendModel):
    """Backend ``PromotionObject`` model generated from the Keepa Java schema."""

    type: PromotionType | None = None
    amount: int | None = None
    discountPercent: int | None = None
    snsBulkDiscountPercent: int | None = None
    sellerId: str | None = None


class Request(KeepaBackendModel):
    """Backend ``Request`` model generated from the Keepa Java schema."""

    parameter: dict[str, str | None] | None = None
    postData: str | None = None
    path: str | None = None


class RequestError(KeepaBackendModel):
    """Backend ``RequestError`` model generated from the Keepa Java schema."""

    pass


class Response(KeepaBackendModel):
    """Backend ``Response`` model generated from the Keepa Java schema."""

    timestamp: int | None = None
    tokensLeft: int | None = None
    refillIn: int | None = None
    refillRate: int | None = None
    requestTime: int | None = None
    processingTimeInMs: int | None = None
    tokenFlowReduction: float | None = None
    tokensConsumed: int | None = None
    status: ResponseStatus | None = None
    statusCode: int | None = None
    products: list[Product | None] | None = None
    categories: dict[int, Category | None] | None = None
    categoryParents: dict[int, Category | None] | None = None
    deals: DealResponse | None = None
    bestSellersList: BestSellers | None = None
    sellers: dict[str, Seller | None] | None = None
    trackings: list[Tracking | None] | None = None
    notifications: list[Notification | None] | None = None
    asinList: list[str | None] | None = None
    totalResults: int | None = None
    sellerIdList: list[str | None] | None = None
    lightningDeals: list[LightningDeal | None] | None = None
    error: RequestError | None = None
    additional: str | None = None


class ReviewObject(KeepaBackendModel):
    """Backend ``ReviewObject`` model generated from the Keepa Java schema."""

    lastUpdate: int | None = None
    ratingCount: list[int | None] | None = None
    reviewCount: list[int | None] | None = None


class Seller(KeepaBackendModel):
    """Backend ``Seller`` model generated from the Keepa Java schema."""

    trackedSince: int | None = None
    domainId: int | None = None
    sellerId: str | None = None
    sellerName: str | None = None
    csv: list[list[int | None] | None] | None = None
    lastUpdate: int | None = None
    shipsFromChina: bool | None = None
    hasFBA: bool | None = None
    totalStorefrontAsins: list[int | None] | None = None
    asinList: list[str | None] | None = None
    asinListLastSeen: list[int | None] | None = None
    totalStorefrontAsinsCSV: list[int | None] | None = None
    sellerCategoryStatistics: list[MerchantCategoryStatistics | None] | None = None
    sellerBrandStatistics: list[MerchantBrandStatistics | None] | None = None
    avgBuyBoxCompetitors: float | None = None
    buyBoxNewOwnershipRate: int | None = None
    buyBoxUsedOwnershipRate: int | None = None
    competitors: list[Competitors | None] | None = None
    address: list[str | None] | None = None
    recentFeedback: list[FeedbackObject | None] | None = None
    lastRatingUpdate: int | None = None
    neutralRating: list[int | None] | None = None
    negativeRating: list[int | None] | None = None
    positiveRating: list[int | None] | None = None
    ratingCount: list[int | None] | None = None
    customerServicesAddress: list[str | None] | None = None
    tradeNumber: str | None = None
    businessName: str | None = None
    vatID: str | None = None
    phoneNumber: str | None = None
    businessType: str | None = None
    shareCapital: str | None = None
    representative: str | None = None
    email: str | None = None
    currentRating: int | None = None
    currentRatingCount: int | None = None
    ratingsLast30Days: int | None = None


class Stats(KeepaBackendModel):
    """Backend ``Stats`` model generated from the Keepa Java schema."""

    current: list[int | None] | None = None
    avg: list[int | None] | None = None
    avg30: list[int | None] | None = None
    avg90: list[int | None] | None = None
    avg180: list[int | None] | None = None
    avg365: list[int | None] | None = None
    atIntervalStart: list[int | None] | None = None
    min: list[list[int | None] | None] | None = None
    minInInterval: list[list[int | None] | None] | None = None
    max: list[list[int | None] | None] | None = None
    maxInInterval: list[list[int | None] | None] | None = None
    isLowest: list[bool | None] | None = None
    isLowest90: list[bool | None] | None = None
    outOfStockCountAmazon30: int | None = None
    outOfStockCountAmazon90: int | None = None
    deltaPercent90_monthlySold: int | None = None
    outOfStockPercentageInInterval: list[int | None] | None = None
    outOfStockPercentage90: list[int | None] | None = None
    outOfStockPercentage30: list[int | None] | None = None
    lightningDealInfo: list[int | None] | None = None
    totalOfferCount: int | None = None
    lastOffersUpdate: int | None = None
    stockPerCondition3rdFBA: list[int | None] | None = None
    stockPerConditionFBM: list[int | None] | None = None
    stockAmazon: int | None = None
    stockBuyBox: int | None = None
    retrievedOfferCount: int | None = None
    buyBoxPrice: int | None = None
    buyBoxShipping: int | None = None
    buyBoxIsUnqualified: bool | None = None
    buyBoxIsShippable: bool | None = None
    buyBoxIsPreorder: bool | None = None
    buyBoxIsFBA: bool | None = None
    lastBuyBoxUpdate: int | None = None
    buyBoxIsUsed: bool | None = None
    buyBoxIsBackorder: bool | None = None
    buyBoxIsAmazon: bool | None = None
    buyBoxIsMAP: bool | None = None
    buyBoxMinOrderQuantity: int | None = None
    buyBoxMaxOrderQuantity: int | None = None
    buyBoxAvailabilityMessage: str | None = None
    buyBoxSellerId: str | None = None
    buyBoxShippingCountry: str | None = None
    buyBoxIsPrimeExclusive: bool | None = None
    buyBoxIsFreeShippingEligible: bool | None = None
    buyBoxIsPrimeEligible: bool | None = None
    buyBoxIsPrimePantry: bool | None = None
    buyBoxStats: dict[str, BuyBoxStatsObject | None] | None = None
    buyBoxSavingBasis: int | None = None
    buyBoxSavingBasisType: str | None = None
    buyBoxSavingPercentage: int | None = None
    buyBoxUsedPrice: int | None = None
    buyBoxUsedShipping: int | None = None
    buyBoxUsedSellerId: str | None = None
    buyBoxUsedIsFBA: bool | None = None
    buyBoxUsedCondition: int | None = None
    buyBoxUsedStats: dict[str, BuyBoxStatsObject | None] | None = None
    isAddonItem: bool | None = None
    sellerIdsLowestFBA: list[str | None] | None = None
    sellerIdsLowestFBM: list[str | None] | None = None
    offerCountFBA: int | None = None
    offerCountFBM: int | None = None
    salesRankDrops30: int | None = None
    salesRankDrops90: int | None = None
    salesRankDrops180: int | None = None
    salesRankDrops365: int | None = None


class Tracking(KeepaBackendModel):
    """Backend ``Tracking`` model generated from the Keepa Java schema."""

    asin: str | None = None
    createDate: int | None = None
    ttl: int | None = None
    expireNotify: bool | None = None
    mainDomainId: int | None = None
    thresholdValues: list[TrackingThresholdValue | None] | None = None
    notifyIf: list[TrackingNotifyIf | None] | None = None
    notificationType: list[bool | None] | None = None
    notificationCSV: list[int | None] | None = None
    individualNotificationInterval: int | None = None
    isActive: bool | None = None
    updateInterval: int | None = None
    metaData: str | None = None


class TrackingNotifyIf(KeepaBackendModel):
    """Backend ``TrackingNotifyIf`` model generated from the Keepa Java schema."""

    domain: int | None = None
    csvType: int | None = None
    notifyIfType: int | None = None


class TrackingRequest(KeepaBackendModel):
    """Backend ``TrackingRequest`` model generated from the Keepa Java schema."""

    asin: str | None = None
    ttl: int | None = None
    expireNotify: bool | None = None
    desiredPricesInMainCurrency: bool | None = None
    mainDomainId: int | None = None
    thresholdValues: list[TrackingThresholdValue | None] | None = None
    notifyIf: list[TrackingNotifyIf | None] | None = None
    notificationType: list[bool | None] | None = None
    individualNotificationInterval: int | None = None
    updateInterval: int | None = None
    metaData: str | None = None


class TrackingThresholdValue(KeepaBackendModel):
    """Backend ``TrackingThresholdValue`` model generated from the Keepa Java schema."""

    thresholdValueCSV: list[int | None] | None = None
    thresholdValue: int | None = None
    domain: int | None = None
    csvType: int | None = None
    isDrop: bool | None = None
    minDeltaAbsolute: int | None = None
    minDeltaPercentage: int | None = None
    deltasAreBetweenNotifications: bool | None = None


class UnitCountObject(KeepaBackendModel):
    """Backend ``UnitCountObject`` model generated from the Keepa Java schema."""

    unitValue: float | None = None
    unitType: str | None = None
    eachUnitCount: float | None = None


class VariationAttributeObject(KeepaBackendModel):
    """Backend ``VariationAttributeObject`` model generated from the Keepa Java schema."""

    dimension: str | None = None
    value: str | None = None


class VariationObject(KeepaBackendModel):
    """Backend ``VariationObject`` model generated from the Keepa Java schema."""

    asin: str | None = None
    attributes: list[VariationAttributeObject | None] | None = None
    image: str | None = None


class Video(KeepaBackendModel):
    """Backend ``Video`` model generated from the Keepa Java schema."""

    title: str | None = None
    image: str | None = None
    duration: int | None = None
    creator: VideoCreatorType | None = None
    name: str | None = None
    url: str | None = None


__all__ = [
    "BACKEND_COMMIT",
    "KeepaBackendModel",
    "AmazonLocale",
    "AvailabilityType",
    "CsvType",
    "DealInterval",
    "DealState",
    "MerchantCsvType",
    "NotificationType",
    "NotifyIfType",
    "OfferCondition",
    "ProductType",
    "PromotionType",
    "ResponseStatus",
    "TrackingNotificationCause",
    "VideoCreatorType",
    "APlus",
    "APlusModule",
    "BestSellers",
    "BuyBoxStatsObject",
    "Category",
    "CategoryTreeEntry",
    "Competitors",
    "Deal",
    "DealDetails",
    "DealRequest",
    "DealResponse",
    "FBAFeesObject",
    "FeedbackObject",
    "Format",
    "HazardousMaterial",
    "Image",
    "LightningDeal",
    "MerchantBrandStatistics",
    "MerchantCategoryStatistics",
    "Notification",
    "Offer",
    "OfferDuplicate",
    "Product",
    "ProductFinderRequest",
    "PromotionObject",
    "Request",
    "RequestError",
    "Response",
    "ReviewObject",
    "Seller",
    "Stats",
    "Tracking",
    "TrackingNotifyIf",
    "TrackingRequest",
    "TrackingThresholdValue",
    "UnitCountObject",
    "VariationAttributeObject",
    "VariationObject",
    "Video",
]

_MODELS: list[type[KeepaBackendModel]] = [
    APlus,
    APlusModule,
    BestSellers,
    BuyBoxStatsObject,
    Category,
    CategoryTreeEntry,
    Competitors,
    Deal,
    DealDetails,
    DealRequest,
    DealResponse,
    FBAFeesObject,
    FeedbackObject,
    Format,
    HazardousMaterial,
    Image,
    LightningDeal,
    MerchantBrandStatistics,
    MerchantCategoryStatistics,
    Notification,
    Offer,
    OfferDuplicate,
    Product,
    ProductFinderRequest,
    PromotionObject,
    Request,
    RequestError,
    Response,
    ReviewObject,
    Seller,
    Stats,
    Tracking,
    TrackingNotifyIf,
    TrackingRequest,
    TrackingThresholdValue,
    UnitCountObject,
    VariationAttributeObject,
    VariationObject,
    Video,
]
for _model in _MODELS:
    _model.model_rebuild()
