"""Generate permissive Pydantic models from Keepa backend Java structs."""

from __future__ import annotations

import keyword
import os
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

import requests

BACKEND_COMMIT = "6e524d13bc25bdbe49be24d59a4b28feb9f98e5d"
BACKEND_SOURCE_DIR_ENV = "KEEPA_BACKEND_SOURCE_DIR"
BACKEND_RAW_BASE = (
    "https://raw.githubusercontent.com/keepacom/api_backend"
    f"/{BACKEND_COMMIT}/src/main/java/com/keepa/api/backend"
)
BACKEND_CONTENTS_URL = (
    "https://api.github.com/repos/keepacom/api_backend/contents/"
    "src/main/java/com/keepa/api/backend/structs"
)

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "keepa" / "models" / "backend.py"
DOC_OUTPUT = ROOT / "docs" / "source" / "backend_model_reference.rst"

JAVA_TYPE_MAP = {
    "String": "str",
    "Integer": "int",
    "int": "int",
    "Long": "int",
    "long": "int",
    "Short": "int",
    "short": "int",
    "Byte": "int",
    "byte": "int",
    "Double": "float",
    "double": "float",
    "Float": "float",
    "float": "float",
    "Boolean": "bool",
    "boolean": "bool",
}


def main() -> None:
    """Generate backend Pydantic models from the pinned Keepa Java source."""
    struct_files = _backend_struct_files()
    sources = {file_name: _backend_source(f"structs/{file_name}") for file_name in struct_files}
    keepa_api_source = _backend_source("KeepaAPI.java")
    declarations = _collect_declarations(sources)
    enum_values = _collect_enum_values(declarations, keepa_api_source)
    class_names = {declaration.name for declaration in declarations if declaration.kind == "class"}
    enum_names = set(enum_values)
    export_names = [
        "BACKEND_COMMIT",
        "KeepaBackendModel",
        *sorted(enum_values),
        *[
            declaration.name
            for declaration in sorted(declarations, key=lambda item: item.name)
            if declaration.kind == "class"
        ],
    ]

    lines = [
        '"""Pydantic models generated from Keepa backend Java structs."""',
        "",
        "# Generated by utilities/generate-backend-models.py; do not edit by hand.",
        "",
        "from __future__ import annotations",
        "",
        "from enum import Enum",
        "",
        "from pydantic import BaseModel, ConfigDict, Field",
        "",
        f'BACKEND_COMMIT = "{BACKEND_COMMIT}"',
        "",
        "",
        "class KeepaBackendModel(BaseModel):",
        '    """Base model for backend response/request structures."""',
        "",
        '    model_config = ConfigDict(extra="allow", coerce_numbers_to_str=True)',
    ]

    for enum_name, values in sorted(enum_values.items()):
        lines.extend(_render_enum(enum_name, values))

    for declaration in sorted(declarations, key=lambda item: item.name):
        if declaration.kind != "class":
            continue
        lines.extend(_render_model(declaration, class_names, enum_names))

    lines.extend(
        [
            "",
            "",
            "__all__ = [",
            *[f'    "{name}",' for name in export_names],
            "]",
            "",
            "_MODELS: list[type[KeepaBackendModel]] = [",
            *[
                f"    {declaration.name},"
                for declaration in sorted(declarations, key=lambda item: item.name)
                if declaration.kind == "class"
            ],
            "]",
            "for _model in _MODELS:",
            "    _model.model_rebuild()",
            "",
        ]
    )

    OUTPUT.write_text("\n".join(lines))
    _write_backend_docs(declarations, enum_values)


def _write_backend_docs(declarations: list[Declaration], enum_values: dict[str, list[str]]) -> None:
    model_names = [
        "KeepaBackendModel",
        *sorted(declaration.name for declaration in declarations if declaration.kind == "class"),
    ]
    lines = [
        ".. Generated by utilities/generate-backend-models.py; do not edit by hand.",
        "",
        "Backend Model API",
        "=================",
        "Every model and enum is generated from the pinned Keepa backend schema.",
        "",
        "Models",
        "------",
        "",
        ".. autosummary::",
        "   :toctree: api/backend/models",
        "   :template: pydantic_model",
        "",
        *[f"   keepa.models.backend.{name}" for name in model_names],
        "",
        "Enums",
        "-----",
        "",
        ".. autosummary::",
        "   :toctree: api/backend/enums",
        "   :template: enum",
        "",
        *[f"   keepa.models.backend.{name}" for name in sorted(enum_values)],
        "",
        "Schema Metadata",
        "---------------",
        "",
        ".. autosummary::",
        "   :toctree: api/backend/data",
        "",
        "   keepa.models.backend.BACKEND_COMMIT",
        "",
    ]
    DOC_OUTPUT.write_text("\n".join(lines))


@dataclass(frozen=True)
class Declaration:
    """Java declaration parsed from the backend source."""

    kind: str
    name: str
    body: str


def _backend_source(filename: str) -> str:
    local_file = _local_backend_file(filename)
    if local_file is not None:
        return local_file.read_text()

    response = requests.get(f"{BACKEND_RAW_BASE}/{filename}", timeout=20)
    response.raise_for_status()
    return response.text


def _backend_struct_files() -> list[str]:
    source_dir = os.environ.get(BACKEND_SOURCE_DIR_ENV)
    if source_dir is not None:
        source_path = Path(source_dir)
        if _local_backend_checkout_matches_commit(source_path):
            return sorted(path.name for path in (source_path / "structs").glob("*.java"))

    response = requests.get(BACKEND_CONTENTS_URL, params={"ref": BACKEND_COMMIT}, timeout=20)
    response.raise_for_status()
    return sorted(item["name"] for item in response.json() if item["name"].endswith(".java"))


def _local_backend_file(filename: str) -> Path | None:
    source_dir = os.environ.get(BACKEND_SOURCE_DIR_ENV)
    if source_dir is None:
        return None
    source_path = Path(source_dir)
    local_file = source_path / filename
    if local_file.is_file() and _local_backend_checkout_matches_commit(source_path):
        return local_file
    return None


def _local_backend_checkout_matches_commit(source_path: Path) -> bool:
    try:
        result = subprocess.run(
            ["git", "-C", str(source_path), "rev-parse", "--show-toplevel"],
            check=True,
            capture_output=True,
            text=True,
        )
        repo_root = Path(result.stdout.strip())
        result = subprocess.run(
            ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return False
    return result.stdout.strip() == BACKEND_COMMIT


def _collect_declarations(sources: dict[str, str]) -> list[Declaration]:
    declarations = []
    declaration_pattern = re.compile(r"public\s+(?:static\s+)?(?:final\s+)?(class|enum)\s+(\w+)")
    for source in map(_strip_comments, sources.values()):
        for match in declaration_pattern.finditer(source):
            brace_start = source.find("{", match.end())
            if brace_start < 0:
                continue
            brace_end = _matching_brace(source, brace_start)
            declarations.append(
                Declaration(match.group(1), match.group(2), source[brace_start + 1 : brace_end])
            )
    return declarations


def _strip_comments(source: str) -> str:
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.S)
    return re.sub(r"//.*", "", source)


def _matching_brace(source: str, brace_start: int) -> int:
    depth = 0
    for index in range(brace_start, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return index
    raise ValueError("No matching brace")


def _collect_enum_values(
    declarations: list[Declaration], keepa_api_source: str
) -> dict[str, list[str]]:
    values = {
        declaration.name: _enum_values(declaration.body)
        for declaration in declarations
        if declaration.kind == "enum"
    }
    response_status = re.search(
        r"public\s+enum\s+ResponseStatus\s*\{(.*?)\}", keepa_api_source, re.S
    )
    if response_status is not None:
        values["ResponseStatus"] = _enum_values(response_status.group(1))
    return values


def _enum_values(enum_body: str) -> list[str]:
    constants_text = enum_body.split(";", 1)[0]
    constants_text = re.sub(r"/\*.*?\*/", "", constants_text, flags=re.S)
    values = []
    for item in _split_top_level(constants_text, ","):
        item = item.strip()
        if not item:
            continue
        match = re.match(r"([A-Za-z_][A-Za-z0-9_]*)", item)
        if match is not None:
            values.append(match.group(1))
    return values


def _split_top_level(text: str, separator: str) -> list[str]:
    parts = []
    depth = 0
    start = 0
    for index, char in enumerate(text):
        if char in "(<[":
            depth += 1
        elif char in ")>]":
            depth -= 1
        elif char == separator and depth == 0:
            parts.append(text[start:index])
            start = index + 1
    parts.append(text[start:])
    return parts


def _render_enum(name: str, values: list[str]) -> list[str]:
    lines = ["", "", f"class {name}(str, Enum):"]
    lines.append('    """Backend enum generated from the Keepa Java schema."""')
    lines.append("")
    if not values:
        lines.append("    pass")
    for value in values:
        lines.append(f'    {value} = "{value}"')
    return lines


def _render_model(
    declaration: Declaration, class_names: set[str], enum_names: set[str]
) -> list[str]:
    fields = _class_fields(declaration.body)
    lines = ["", "", f"class {declaration.name}(KeepaBackendModel):"]
    lines.append(
        f'    """Backend ``{declaration.name}`` model generated from the Keepa Java schema."""'
    )
    lines.append("")
    if not fields:
        lines.append("    pass")
        return lines
    seen = set()
    for java_type, name in fields:
        if name in seen:
            continue
        seen.add(name)
        python_name = _python_field_name(name)
        annotation = _python_type(java_type, class_names, enum_names)
        if python_name == name:
            lines.append(f"    {python_name}: {annotation} | None = None")
        else:
            lines.append(
                f'    {python_name}: {annotation} | None = Field(default=None, alias="{name}")'
            )
    return lines


def _python_field_name(name: str) -> str:
    if not name.isidentifier() or keyword.iskeyword(name) or name == "l":
        return f"{name}_"
    return name


def _class_fields(class_body: str) -> list[tuple[str, str]]:
    class_body = _remove_nested_declarations(class_body)
    fields = []
    for match in re.finditer(
        r"public\s+(?!(?:static|final|transient)\b)([\w\[\].<>, ?]+)\s+(\w+)"
        r"(?:\s*=\s*[^;]+)?\s*;",
        class_body,
    ):
        java_type = " ".join(match.group(1).replace("?", "").split())
        fields.append((java_type, match.group(2)))
    return fields


def _remove_nested_declarations(class_body: str) -> str:
    declaration_pattern = re.compile(r"public\s+(?:static\s+)?(?:final\s+)?(?:class|enum)\s+\w+")
    output = []
    cursor = 0
    for match in declaration_pattern.finditer(class_body):
        brace_start = class_body.find("{", match.end())
        if brace_start < 0:
            continue
        brace_end = _matching_brace(class_body, brace_start)
        output.append(class_body[cursor : match.start()])
        cursor = brace_end + 1
    output.append(class_body[cursor:])
    return "".join(output)


def _python_type(java_type: str, class_names: set[str], enum_names: set[str]) -> str:
    java_type = java_type.strip()
    if java_type.endswith("[][]"):
        item_type = _python_type(java_type[:-4], class_names, enum_names)
        return f"list[list[{item_type} | None] | None]"
    if java_type.endswith("[]"):
        item_type = _python_type(java_type[:-2], class_names, enum_names)
        return f"list[{item_type} | None]"

    generic_match = re.match(r"(?:HashMap|LinkedHashMap)<(.+)>", java_type)
    if generic_match is not None:
        key_type, value_type = _split_top_level(generic_match.group(1), ",")
        return (
            f"dict[{_python_type(key_type, class_names, enum_names)}, "
            f"{_python_type(value_type, class_names, enum_names)} | None]"
        )

    if java_type == "KeepaAPI.ResponseStatus":
        return "ResponseStatus"
    if java_type in JAVA_TYPE_MAP:
        return JAVA_TYPE_MAP[java_type]
    if java_type in class_names or java_type in enum_names:
        return java_type
    nested_type = java_type.rsplit(".", 1)[-1]
    if nested_type in class_names or nested_type in enum_names:
        return nested_type
    raise ValueError(f"Unsupported Java type: {java_type}")


if __name__ == "__main__":
    main()
